[tool.poetry]
name = "quantization-examples"
version = "0.1.0"
description = ""
authors = ["TensorRT LLM [90828364+tensorrt-cicd@users.noreply.github.com]"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
datasets = "3.1.0"
rouge-score = "^0.1.2"
transformers-stream-generator = "0.0.4"
tiktoken = "^0.12.0"
mpmath = "1.3.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
