

class UBBuffer:
    @property
    def size(self) -> int: ...

    @property
    def addr(self) -> int: ...

    @property
    def handle(self) -> int: ...

    def invalid(self) -> bool: ...

def ub_initialize(arg: int, /) -> None: ...

def ub_is_initialized() -> bool: ...

def ub_allocate(arg: int, /) -> UBBuffer: ...

def ub_deallocate(arg: int, /) -> None: ...

def ub_get(arg: int, /) -> UBBuffer: ...

def ub_supported() -> bool: ...

def initialize_userbuffers_manager(arg0: int, arg1: int, arg2: int, arg3: int, arg4: int, arg5: int, arg6: bool, /) -> None: ...
