moe_backend: "CUTLASS"
kv_cache_dtype: "fp8"
use_cuda_graph: true
cuda_graph_padding_enabled: true
cuda_graph_batch_sizes:
- 1
- 2
- 4
- 8
- 16
- 32
- 64
cuda_graph_max_batch_size: 0
print_iter_log: true
disable_overlap_scheduler: false
moe_max_num_tokens: 3072
enable_attention_dp: true
