# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import trtllm_engine_pb2 as trtllm__engine__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in trtllm_engine_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TrtLlmEngineStub(object):
    """TensorRT-LLM gRPC Engine Service

    This service provides high-performance inference for LLMs using TensorRT-LLM.
    It accepts pre-tokenized requests and returns raw token IDs, enabling efficient
    binary communication with external routers (e.g., sgl-router).

    Key Design Principles:
    - Token IDs only: No text in requests or responses (router handles tokenization)
    - Streaming delta mode: Chunks contain only new tokens since last chunk
    - Full feature support: All TensorRT-LLM capabilities exposed

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Generate = channel.unary_stream(
                '/trtllm.TrtLlmEngine/Generate',
                request_serializer=trtllm__engine__pb2.GenerateRequest.SerializeToString,
                response_deserializer=trtllm__engine__pb2.GenerateResponse.FromString,
                _registered_method=True)
        self.Embed = channel.unary_unary(
                '/trtllm.TrtLlmEngine/Embed',
                request_serializer=trtllm__engine__pb2.EmbedRequest.SerializeToString,
                response_deserializer=trtllm__engine__pb2.EmbedResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/trtllm.TrtLlmEngine/HealthCheck',
                request_serializer=trtllm__engine__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=trtllm__engine__pb2.HealthCheckResponse.FromString,
                _registered_method=True)
        self.Abort = channel.unary_unary(
                '/trtllm.TrtLlmEngine/Abort',
                request_serializer=trtllm__engine__pb2.AbortRequest.SerializeToString,
                response_deserializer=trtllm__engine__pb2.AbortResponse.FromString,
                _registered_method=True)
        self.GetModelInfo = channel.unary_unary(
                '/trtllm.TrtLlmEngine/GetModelInfo',
                request_serializer=trtllm__engine__pb2.GetModelInfoRequest.SerializeToString,
                response_deserializer=trtllm__engine__pb2.GetModelInfoResponse.FromString,
                _registered_method=True)
        self.GetServerInfo = channel.unary_unary(
                '/trtllm.TrtLlmEngine/GetServerInfo',
                request_serializer=trtllm__engine__pb2.GetServerInfoRequest.SerializeToString,
                response_deserializer=trtllm__engine__pb2.GetServerInfoResponse.FromString,
                _registered_method=True)


class TrtLlmEngineServicer(object):
    """TensorRT-LLM gRPC Engine Service

    This service provides high-performance inference for LLMs using TensorRT-LLM.
    It accepts pre-tokenized requests and returns raw token IDs, enabling efficient
    binary communication with external routers (e.g., sgl-router).

    Key Design Principles:
    - Token IDs only: No text in requests or responses (router handles tokenization)
    - Streaming delta mode: Chunks contain only new tokens since last chunk
    - Full feature support: All TensorRT-LLM capabilities exposed

    """

    def Generate(self, request, context):
        """Generate tokens from pre-tokenized input
        Returns a stream of responses containing token IDs
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Embed(self, request, context):
        """Generate embeddings from pre-tokenized input (for embedding models)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check endpoint
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Abort(self, request, context):
        """Abort a running generation request
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetModelInfo(self, request, context):
        """Get model information (vocab size, max lengths, etc.)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetServerInfo(self, request, context):
        """Get server information (version, parallelism, etc.)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TrtLlmEngineServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Generate': grpc.unary_stream_rpc_method_handler(
                    servicer.Generate,
                    request_deserializer=trtllm__engine__pb2.GenerateRequest.FromString,
                    response_serializer=trtllm__engine__pb2.GenerateResponse.SerializeToString,
            ),
            'Embed': grpc.unary_unary_rpc_method_handler(
                    servicer.Embed,
                    request_deserializer=trtllm__engine__pb2.EmbedRequest.FromString,
                    response_serializer=trtllm__engine__pb2.EmbedResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=trtllm__engine__pb2.HealthCheckRequest.FromString,
                    response_serializer=trtllm__engine__pb2.HealthCheckResponse.SerializeToString,
            ),
            'Abort': grpc.unary_unary_rpc_method_handler(
                    servicer.Abort,
                    request_deserializer=trtllm__engine__pb2.AbortRequest.FromString,
                    response_serializer=trtllm__engine__pb2.AbortResponse.SerializeToString,
            ),
            'GetModelInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetModelInfo,
                    request_deserializer=trtllm__engine__pb2.GetModelInfoRequest.FromString,
                    response_serializer=trtllm__engine__pb2.GetModelInfoResponse.SerializeToString,
            ),
            'GetServerInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetServerInfo,
                    request_deserializer=trtllm__engine__pb2.GetServerInfoRequest.FromString,
                    response_serializer=trtllm__engine__pb2.GetServerInfoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'trtllm.TrtLlmEngine', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('trtllm.TrtLlmEngine', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TrtLlmEngine(object):
    """TensorRT-LLM gRPC Engine Service

    This service provides high-performance inference for LLMs using TensorRT-LLM.
    It accepts pre-tokenized requests and returns raw token IDs, enabling efficient
    binary communication with external routers (e.g., sgl-router).

    Key Design Principles:
    - Token IDs only: No text in requests or responses (router handles tokenization)
    - Streaming delta mode: Chunks contain only new tokens since last chunk
    - Full feature support: All TensorRT-LLM capabilities exposed

    """

    @staticmethod
    def Generate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/trtllm.TrtLlmEngine/Generate',
            trtllm__engine__pb2.GenerateRequest.SerializeToString,
            trtllm__engine__pb2.GenerateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Embed(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trtllm.TrtLlmEngine/Embed',
            trtllm__engine__pb2.EmbedRequest.SerializeToString,
            trtllm__engine__pb2.EmbedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trtllm.TrtLlmEngine/HealthCheck',
            trtllm__engine__pb2.HealthCheckRequest.SerializeToString,
            trtllm__engine__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Abort(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trtllm.TrtLlmEngine/Abort',
            trtllm__engine__pb2.AbortRequest.SerializeToString,
            trtllm__engine__pb2.AbortResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetModelInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trtllm.TrtLlmEngine/GetModelInfo',
            trtllm__engine__pb2.GetModelInfoRequest.SerializeToString,
            trtllm__engine__pb2.GetModelInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetServerInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trtllm.TrtLlmEngine/GetServerInfo',
            trtllm__engine__pb2.GetServerInfoRequest.SerializeToString,
            trtllm__engine__pb2.GetServerInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
