# The overlap scheduler for context servers is currently disabled, as it is
# not yet supported in disaggregated context server architectures.
disable_overlap_scheduler: True
cache_transceiver_config:
  backend: UCX
  max_tokens_in_buffer: 2048
  # Optional: transmission_data_type: float16  # Defaults to float16, can also use float32, bfloat16, float8
