runtime: trtllm
compile_backend: torch-cudagraph
transforms:
  fuse_gemms_mixed_children:
    enabled: false
  mlir_elementwise_fusion:
    enabled: true
  match_swiglu_pattern:
    enabled: true
  match_nvfp4_swiglu_pattern:
    enabled: true
  fuse_nvfp4_moe:
    allow_different_input_scales: true
  fuse_nvfp4_swiglu:
    enabled: true
  fuse_swiglu:
    enabled: true
  multi_stream_moe:
    enabled: true
  insert_cached_mla_attention:
    backend: trtllm_mla
  fuse_rope_into_trtllm_mla:
    enabled: true
  multi_stream_mla_attn:
    enabled: true
  fuse_allreduce_residual_rmsnorm:
    enabled: true
  detect_sharding:
    allreduce_strategy: SYMM_MEM
    allgather_strategy: SYMM_MEM
    shard_all_unprocessed: true
    simple_shard_filter: "lm_head"
  cleanup_identity_dtype_cast:
    enabled: true
  gather_logits_before_lm_head:
    enabled: true
  compile_model:
    piecewise_enabled: true
    piecewise_num_tokens: [256, 512, 1024, 2048, 3072, 4096, 5120, 6144, 8192]
