#!/usr/bin/env python3
"""Build Slurm job scripts for TRT-LLM test workflows.

Generates scripts for:

  pytest  -> Category 2 (non-perf-sanity pytest)
  custom  -> Category 3 (arbitrary user command/script)
  bench   -> Category 6 (trtllm-bench throughput/latency)
  eval    -> Category 5 (trtllm-eval accuracy)

Not covered:
  - Category 1 (local Docker) is not a Slurm workflow.
  - Category 4 (perf-sanity / benchmark) is generated by submit.py, which
    derives Slurm parameters from the benchmark config YAML.

Argument groups by functionality:

  Slurm directives          -> rendered into #SBATCH lines
  Container / srun          -> rendered into the srun invocation
  Category-specific body    -> rendered into the script payload

Usage:
  build_slurm_script.py pytest --test-cmd "pytest ..."        [common args]
  build_slurm_script.py custom --custom-cmd "bash foo.sh"
                               --run-script /path/slurm_run_custom.sh
                                                              [common args]
  build_slurm_script.py bench  --bench-cmd "trtllm-bench ... prepare-dataset ... && trtllm-bench ... throughput ..."
                                                              [common args]
  build_slurm_script.py eval   --eval-cmd "trtllm-eval ..."   [common args]
"""

from __future__ import annotations

import argparse
import os
import sys
from datetime import datetime
from pathlib import Path

# ---------------------------------------------------------------------------
# Templates
#
# Placeholders use the <PLACEHOLDER> convention.
# Substitution is plain string replace -- no format()/Template -- to avoid
# escaping every bash ${VAR} / ${!PMI@} / ${foo:-0}.
# ---------------------------------------------------------------------------

# Inserted into the bench-run / eval srun bash block when ntasks == 1, so the
# process skips MPI init entirely and avoids dynamic-spawn (MPI_ERR_SPAWN)
# failures under a PMIx-managed step. Empty string when ntasks > 1.
MPI_CLEANUP_BLOCK = """    # Single-task job: clear MPI/SLURM env vars to prevent MPI init / dynamic spawn
    for v in ${!PMI@} ${!PMIX@} ${!MPI@} ${!OMPI@} ${!SLURM@}; do
      if [ "$v" != "SLURM_PROCID" ] && [ "$v" != "SLURM_LOCALID" ]; then
        unset "$v"
      fi
    done
"""

INSTALL_SRUN_FRAGMENT = """\
# Step 1: Install TRT-LLM (one task per node)
<INSTALL_SRUN_BLOCK>
  bash -c '
    set -euo pipefail
    echo "Node ${SLURM_NODEID:-0}: Installing TRT-LLM from source..."
    cd <PROJECT_PATH>
    pip install -e . 2>&1 | tail -5
    pip install -r requirements-dev.txt 2>&1 | tail -5
    echo "Node ${SLURM_NODEID:-0}: Install complete"
  '

"""

EVAL_INSTALL_SRUN_FRAGMENT = """\
# Step 1: Install TRT-LLM and eval dependencies (one task per node)
<INSTALL_SRUN_BLOCK>
  bash -c '
    set -euo pipefail
    echo "Node ${SLURM_NODEID:-0}: Installing TRT-LLM and eval dependencies..."
    cd <PROJECT_PATH>
    pip install -e . 2>&1 | tail -5
    pip install -r requirements-dev.txt 2>&1 | tail -3
    if [ -f examples/trtllm-eval/requirements.txt ]; then
      pip install -r examples/trtllm-eval/requirements.txt 2>&1 | tail -3
    fi
    echo "Node ${SLURM_NODEID:-0}: Install complete"
  '

"""

PYTEST_BODY = """\

set -euo pipefail

echo "Job $SLURM_JOB_ID started on $(hostname) at $(date)"
echo "Nodes: $SLURM_JOB_NUM_NODES, Tasks: $SLURM_NTASKS"

<INSTALL_BLOCK><TEST_STEP_COMMENT><SRUN_BLOCK>
  bash -c '
    nvidia-smi
    # Single-node jobs: clear MPI/SLURM env vars to prevent false MPI init
    if [ "${SLURM_JOB_NUM_NODES:-1}" -eq 1 ]; then
      for v in ${!PMI@} ${!PMIX@} ${!MPI@} ${!OMPI@} ${!SLURM@}; do
        if [ "$v" != "SLURM_PROCID" ]; then
          unset "$v"
        fi
      done
    fi
    export LLM_MODELS_ROOT=<LLM_MODELS_ROOT>
    cd <PROJECT_PATH>
    <TEST_CMD>
  '

exit_code=$?
echo "Job $SLURM_JOB_ID finished at $(date) with exit code $exit_code"
exit $exit_code
"""

CUSTOM_BODY = """\

set -euo pipefail

echo "Job $SLURM_JOB_ID started on $(hostname) at $(date)"
echo "Nodes: $SLURM_JOB_NUM_NODES, Tasks: $SLURM_NTASKS"

export CUSTOM_COMMAND="<CUSTOM_CMD>"
export CUSTOM_ENV="<CUSTOM_ENV>"
export CUSTOM_WORKDIR="<CUSTOM_WORKDIR>"
export llmSrcNode="<PROJECT_PATH>"

<INSTALL_BLOCK># Step 2: Run custom command
<SRUN_BLOCK>
  <RUN_SCRIPT>

exit_code=$?
echo "Job $SLURM_JOB_ID finished at $(date) with exit code $exit_code"
exit $exit_code
"""

BENCH_PREP_FRAGMENT = """\
# Step 2: Prepare benchmark dataset (single process; MPI mode matches bench-run)
<PREP_SRUN_BLOCK>
  bash -c '
    set -euo pipefail
    nvidia-smi
    cd <PROJECT_PATH>
    <PREP_CMD>
  '

"""

BENCH_BODY = """\

set -euo pipefail

echo "Job $SLURM_JOB_ID started on $(hostname) at $(date)"
echo "Nodes: $SLURM_JOB_NUM_NODES, Tasks: $SLURM_NTASKS"

<INSTALL_BLOCK><PREP_BLOCK># Step 3: Run benchmark
<BENCH_RUN_SRUN_BLOCK>
  bash -c '
    set -euo pipefail
<MPI_CLEANUP>    cd <PROJECT_PATH>
    <BENCH_RUN_CMD>
  '

exit_code=$?
echo "Job $SLURM_JOB_ID finished at $(date) with exit code $exit_code"
exit $exit_code
"""

EVAL_BODY = """\

set -euo pipefail

echo "Job $SLURM_JOB_ID started on $(hostname) at $(date)"
echo "Nodes: $SLURM_JOB_NUM_NODES, Tasks: $SLURM_NTASKS"

<INSTALL_BLOCK># Step 2: Run eval
<SRUN_BLOCK>
  bash -c '
    set -euo pipefail
    nvidia-smi
<MPI_CLEANUP>    export LLM_MODELS_ROOT=<LLM_MODELS_ROOT>
    cd <PROJECT_PATH>
    <EVAL_CMD>
  '

exit_code=$?
echo "Job $SLURM_JOB_ID finished at $(date) with exit code $exit_code"
exit $exit_code
"""

# ---------------------------------------------------------------------------
# Builders
# ---------------------------------------------------------------------------


def build_sbatch_header(job_name: str, args: argparse.Namespace) -> str:
    """Render the #SBATCH directives.

    --gres is emitted only when a non-empty value is supplied; otherwise the
    line is dropped entirely (matches SKILL.md GRES_FLAG handling).
    """
    lines = [
        "#!/bin/bash",
        f"#SBATCH --job-name={job_name}",
        f"#SBATCH --output={args.log_dir}/{job_name}_%j.out",
        f"#SBATCH --error={args.log_dir}/{job_name}_%j.err",
        f"#SBATCH --nodes={args.nodes}",
        f"#SBATCH --ntasks={args.ntasks}",
        f"#SBATCH --ntasks-per-node={args.ntasks_per_node}",
    ]
    if args.gres:
        lines.append(f"#SBATCH --gres={args.gres}")
    lines += [
        f"#SBATCH --time={args.time_limit}",
        f"#SBATCH --partition={args.partition}",
        f"#SBATCH --account={args.account}",
    ]
    return "\n".join(lines) + "\n"


def build_srun_block(
    container_workdir: str,
    mpi: str,
    args: argparse.Namespace,
    ntasks: int | None = None,
    nodes: int | None = None,
    ntasks_per_node: int | None = None,
) -> str:
    """Render the srun invocation up to (but not including) the payload.

    The caller appends either `bash -c '...'` (pytest/eval) or a script path
    (custom) on the following line.

    nodes:           when provided, inserts an explicit --nodes override (used by
        the bench prep step to pin dataset prep to a single node).
    ntasks:          when provided, inserts an explicit --ntasks override (used by
        the bench prep step to force single-process dataset prep: -N 1 -n 1).
    ntasks_per_node: when provided, inserts --ntasks-per-node (used by the
        install step to run exactly one installer task per allocated node).
    """
    lines = ["srun -l \\"]
    if nodes is not None:
        lines.append(f"  --nodes={nodes} \\")
    if ntasks is not None:
        lines.append(f"  --ntasks={ntasks} \\")
    if ntasks_per_node is not None:
        lines.append(f"  --ntasks-per-node={ntasks_per_node} \\")
    lines += [
        f"  --container-image={args.docker_image} \\",
        f"  --container-name={args.container_name} \\",
        f"  --container-mounts={args.container_mounts} \\",
        f"  --container-workdir={container_workdir} \\",
        "  --kill-on-bad-exit=1 \\",
    ]
    if mpi and mpi != "none":
        lines.append(f"  --mpi={mpi} \\")
    return "\n".join(lines)


def substitute(template: str, values: dict) -> str:
    out = template
    for k, v in values.items():
        out = out.replace(f"<{k}>", v)
    return out


def build_pytest(args: argparse.Namespace) -> str:
    job_name = f"{args.model_name}_auto_test"
    install_srun = build_srun_block(args.project_path, "none", args, ntasks=1, ntasks_per_node=1)
    install_block = substitute(
        INSTALL_SRUN_FRAGMENT,
        {
            "INSTALL_SRUN_BLOCK": install_srun,
            "PROJECT_PATH": args.project_path,
        },
    )
    body = substitute(
        PYTEST_BODY,
        {
            "INSTALL_BLOCK": install_block,
            "TEST_STEP_COMMENT": "# Step 2: Run tests\n",
            "SRUN_BLOCK": build_srun_block(
                args.container_workdir, args.mpi, args, ntasks=1, ntasks_per_node=1
            ),
            "LLM_MODELS_ROOT": args.llm_models_root,
            "PROJECT_PATH": args.project_path,
            "TEST_CMD": args.test_cmd,
        },
    )
    return build_sbatch_header(job_name, args) + body


def build_custom(args: argparse.Namespace) -> str:
    job_name = f"{args.model_name}_custom"
    custom_workdir = args.custom_workdir or args.project_path
    install_srun = build_srun_block(args.project_path, "none", args, ntasks=1, ntasks_per_node=1)
    install_block = substitute(
        INSTALL_SRUN_FRAGMENT,
        {
            "INSTALL_SRUN_BLOCK": install_srun,
            "PROJECT_PATH": args.project_path,
        },
    )
    body = substitute(
        CUSTOM_BODY,
        {
            "INSTALL_BLOCK": install_block,
            "SRUN_BLOCK": build_srun_block(
                custom_workdir, args.mpi, args, ntasks=1, ntasks_per_node=1
            ),
            "CUSTOM_CMD": args.custom_cmd,
            "CUSTOM_ENV": args.custom_env,
            "CUSTOM_WORKDIR": custom_workdir,
            "PROJECT_PATH": args.project_path,
            "RUN_SCRIPT": args.run_script,
        },
    )
    return build_sbatch_header(job_name, args) + body


def _resolve_pmix(args: argparse.Namespace) -> str:
    # bench/eval auto-promote to a pmix plugin when --ntasks > 1. Honor an
    # explicit pmix variant passed via --mpi (from slurm_env.pmix.preferred,
    # populated by case-executor's detect_slurm_env.sh, e.g. 'pmix_v5');
    # otherwise fall back to the bare 'pmix' plugin name.
    if isinstance(args.mpi, str) and args.mpi.startswith("pmix"):
        return args.mpi
    return "pmix"


def _split_bench_cmd(bench_cmd: str) -> tuple[str, str]:
    """Split a bench_cmd of the form '<prep> && <run>' into (prep, run).

    When no '&&' is present, returns ("", bench_cmd) so the prep srun block
    runs the install only (no dataset prep) and the full command runs as the
    benchmark step. Raises SystemExit when more than one '&&' is found.
    """
    parts = [p.strip() for p in bench_cmd.split("&&")]
    if len(parts) == 1:
        return "", parts[0]
    if len(parts) != 2:
        raise SystemExit(
            "bench: --bench-cmd must contain at most one '&&' separator "
            "between the prepare-dataset step and the throughput/latency step. "
            f"Got {len(parts)} part(s)."
        )
    return parts[0], parts[1]


def build_bench(args: argparse.Namespace) -> str:
    prep_cmd, bench_run_cmd = _split_bench_cmd(args.bench_cmd)
    if args.ntasks > 1 and "trtllm-llmapi-launch" not in bench_run_cmd:
        bench_run_cmd = "trtllm-llmapi-launch " + bench_run_cmd

    # Step 1: Install — single-process pip install; no MPI needed.
    install_srun = build_srun_block(args.project_path, "none", args, ntasks=1, ntasks_per_node=1)
    install_block = substitute(
        INSTALL_SRUN_FRAGMENT,
        {
            "INSTALL_SRUN_BLOCK": install_srun,
            "PROJECT_PATH": args.project_path,
        },
    )

    # Step 2: prepare-dataset always runs on exactly one process on one node
    # (-N 1 -n 1) regardless of how many nodes/GPUs the bench allocates.
    # Step 3: bench-run uses pmix only when ntasks > 1.
    # trtllm-bench imports mpi4py at module load, which auto-inits MPI when PMI
    # env vars are present. For multi-task runs OpenMPI requires srun to provide
    # a PMI/PMIx runtime. For single-task runs, dropping --mpi=pmix and clearing
    # PMI/SLURM env vars in the bash block lets the process skip MPI init
    # entirely and avoids dynamic-spawn (MPI_ERR_SPAWN) failures under PMIx.
    run_mpi = "pmix" if args.ntasks > 1 else "none"
    mpi_cleanup = "" if args.ntasks > 1 else MPI_CLEANUP_BLOCK
    prep_srun = build_srun_block(
        args.project_path, run_mpi, args, ntasks=1, nodes=1, ntasks_per_node=1
    )
    bench_run_srun = build_srun_block(
        args.project_path, run_mpi, args, ntasks=args.ntasks, ntasks_per_node=args.ntasks_per_node
    )

    prep_block = substitute(
        BENCH_PREP_FRAGMENT,
        {
            "PREP_SRUN_BLOCK": prep_srun,
            "PROJECT_PATH": args.project_path,
            "PREP_CMD": prep_cmd,
        },
    )

    job_name = f"{args.model_name}_bench"
    body = substitute(
        BENCH_BODY,
        {
            "INSTALL_BLOCK": install_block,
            "PREP_BLOCK": prep_block,
            "BENCH_RUN_SRUN_BLOCK": bench_run_srun,
            "PROJECT_PATH": args.project_path,
            "BENCH_RUN_CMD": bench_run_cmd,
            "MPI_CLEANUP": mpi_cleanup,
        },
    )
    return build_sbatch_header(job_name, args) + body


def build_eval(args: argparse.Namespace) -> str:
    # trtllm-eval is single-node only. Multi-node accuracy must go through the
    # perf-sanity path (submit.py with accuracy.enable_accuracy_test: true).
    if args.nodes > 1:
        raise SystemExit(
            "eval: trtllm-eval is single-node only (got --nodes="
            f"{args.nodes}). For multi-node accuracy, fall back to the "
            "perf-sanity path: generate a benchmark config with "
            "accuracy.enable_accuracy_test: true and submit via "
            "submit.py."
        )
    eval_cmd = args.eval_cmd
    if args.ntasks > 1 and "trtllm-llmapi-launch" not in eval_cmd:
        eval_cmd = "trtllm-llmapi-launch " + eval_cmd
    # trtllm-eval imports mpi4py at module load, which auto-inits MPI when PMI
    # env vars are present. For multi-task runs OpenMPI requires srun to provide
    # a PMI/PMIx runtime. For single-task runs, dropping --mpi=pmix and clearing
    # PMI/SLURM env vars in the bash block lets the process skip MPI init
    # entirely and avoids dynamic-spawn (MPI_ERR_SPAWN) failures under PMIx.
    mpi = "pmix" if args.ntasks > 1 else "none"
    mpi_cleanup = "" if args.ntasks > 1 else MPI_CLEANUP_BLOCK
    job_name = f"{args.model_name}_eval"
    install_srun = build_srun_block(args.project_path, "none", args, ntasks=1, ntasks_per_node=1)
    install_block = substitute(
        EVAL_INSTALL_SRUN_FRAGMENT,
        {
            "INSTALL_SRUN_BLOCK": install_srun,
            "PROJECT_PATH": args.project_path,
        },
    )
    body = substitute(
        EVAL_BODY,
        {
            "INSTALL_BLOCK": install_block,
            "SRUN_BLOCK": build_srun_block(
                args.project_path,
                mpi,
                args,
                ntasks=args.ntasks,
                ntasks_per_node=args.ntasks_per_node,
            ),
            "PROJECT_PATH": args.project_path,
            "LLM_MODELS_ROOT": args.llm_models_root,
            "EVAL_CMD": eval_cmd,
            "MPI_CLEANUP": mpi_cleanup,
        },
    )
    return build_sbatch_header(job_name, args) + body


CATEGORY_BUILDERS = {
    "pytest": build_pytest,
    "custom": build_custom,
    "bench": build_bench,
    "eval": build_eval,
}

# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def _add_common_args(p: argparse.ArgumentParser) -> None:
    sbatch = p.add_argument_group(
        "Slurm directives (#SBATCH lines)",
        "Values rendered literally into the #SBATCH header.",
    )
    sbatch.add_argument(
        "--model-name", required=True, help="Short model name; becomes the job-name prefix."
    )
    sbatch.add_argument(
        "--log-dir",
        default=None,
        help=(
            "Directory rendered into #SBATCH --output/--error "
            "in the .slurm script. For remote_slurm runs this "
            "is the REMOTE path on the cluster filesystem; the "
            "script does NOT create this directory locally. "
            "Required for pytest/custom. For bench/eval, "
            "defaults to "
            "<project-path>/work_dirs/<model-name>_<timestamp>."
        ),
    )
    sbatch.add_argument(
        "--local-log-dir",
        default=None,
        help=(
            "Path on the LOCAL (orchestrating) node to mkdir "
            "before writing the script. Use this for "
            "remote_slurm runs where --log-dir points to a "
            "cluster-only path. When unset, defaults to "
            "--log-dir (preserves local_slurm/local_docker "
            "behavior)."
        ),
    )
    sbatch.add_argument("--partition", required=True)
    sbatch.add_argument("--account", required=True)
    sbatch.add_argument("--time-limit", default="02:00:00")
    sbatch.add_argument("--nodes", type=int, default=1)
    sbatch.add_argument("--ntasks", type=int, default=1)
    sbatch.add_argument("--ntasks-per-node", type=int, default=1)
    sbatch.add_argument(
        "--gres",
        default="",
        help="Value for --gres (e.g. 'gpu:4'). Empty omits the line entirely.",
    )

    container = p.add_argument_group(
        "Container / srun",
        "Values rendered into the srun invocation.",
    )
    container.add_argument("--docker-image", required=True)
    container.add_argument(
        "--container-mounts", required=True, help="Comma-separated bind mounts for pyxis."
    )
    container.add_argument(
        "--container-name", default=None, help="Default: <model-name>_<category>."
    )
    container.add_argument("--container-workdir", default=None, help="Default: --project-path.")
    container.add_argument(
        "--project-path", required=True, help="Absolute path to the TRT-LLM repo root."
    )
    container.add_argument(
        "--mpi",
        default="none",
        help=(
            "MPI plugin for srun. 'none' disables --mpi. Otherwise the value "
            "is passed through verbatim (e.g. 'pmix', 'pmix_v3', 'pmix_v5'); "
            "resolve it from slurm_env.pmix.preferred (populated by "
            "case-executor's detect_slurm_env.sh). For bench/eval, "
            "overridden to a pmix variant when --ntasks > 1."
        ),
    )
    container.add_argument(
        "--llm-models-root",
        default="/scratch.trt_llm_data/llm-models/",
        help="Path exported as LLM_MODELS_ROOT inside the container.",
    )

    output = p.add_argument_group("Output")
    output.add_argument("--output", default=None, help="Write to this path. Default: stdout.")


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    sub = p.add_subparsers(dest="category", required=True, metavar="{pytest,custom,bench,eval}")

    pp = sub.add_parser("pytest", help="Non-perf-sanity pytest (Category 2)")
    _add_common_args(pp)
    body = pp.add_argument_group("pytest body")
    body.add_argument(
        "--test-cmd", required=True, help="Pytest command string run inside the container."
    )

    cp = sub.add_parser("custom", help="Custom command/script (Category 3)")
    _add_common_args(cp)
    body = cp.add_argument_group("custom body")
    body.add_argument(
        "--custom-cmd", required=True, help="Command string. 'bash <script>' when wrapping a file."
    )
    body.add_argument(
        "--custom-env", default="", help="Space-separated KEY=VALUE pairs exported in-container."
    )
    body.add_argument(
        "--custom-workdir",
        default=None,
        help="In-container cwd for the command. Default: --project-path.",
    )
    body.add_argument(
        "--run-script", required=True, help="In-container path to slurm_run_custom.sh."
    )

    bp = sub.add_parser("bench", help="trtllm-bench throughput/latency (Category 6)")
    _add_common_args(bp)
    body = bp.add_argument_group("bench body")
    body.add_argument(
        "--bench-cmd",
        required=True,
        help=(
            "Two trtllm-bench commands joined by '&&': "
            "'trtllm-bench ... prepare-dataset ... && trtllm-bench ... throughput ...'. "
            "The first (prepare-dataset) always runs single-process (-N 1 -n 1). "
            "The second (throughput/latency) is the main benchmark run."
        ),
    )

    ep = sub.add_parser("eval", help="trtllm-eval accuracy workflow (Category 5)")
    _add_common_args(ep)
    body = ep.add_argument_group("eval body")
    body.add_argument("--eval-cmd", required=True, help="Full trtllm-eval command.")

    return p


def _apply_defaults(args: argparse.Namespace) -> None:
    if args.container_name is None:
        args.container_name = f"{args.model_name}_{args.category}"
    if args.container_workdir is None:
        args.container_workdir = args.project_path
    if args.log_dir is None:
        if args.category in {"bench", "eval"}:
            ts = datetime.now().strftime("%Y%m%d_%H%M%S")
            args.log_dir = os.path.join(args.project_path, "work_dirs", f"{args.model_name}_{ts}")
        else:
            sys.exit(f"--log-dir is required for category '{args.category}'")
    # For remote_slurm, --log-dir is a cluster-only path that does not exist on
    # the orchestrating host. Callers should pass --local-log-dir pointing to
    # the local work_dir; we mkdir that path here. The --log-dir value still
    # gets baked into the rendered #SBATCH --output/--error lines.
    mkdir_target = args.local_log_dir or args.log_dir
    os.makedirs(mkdir_target, exist_ok=True)


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    _apply_defaults(args)

    script = CATEGORY_BUILDERS[args.category](args)

    if args.output:
        out_path = Path(args.output)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(script)
        os.chmod(out_path, 0o755)
        print(f"Wrote {out_path}", file=sys.stderr)
    else:
        sys.stdout.write(script)

    return 0


if __name__ == "__main__":
    sys.exit(main())
