blank_issues_enabled: false
contact_links:
  - name: 🤔 Questions
    url: https://github.com/NVIDIA/TensorRT-LLM/discussions
    about: Ask questions and discuss with other TensorRT-LLM community members
