# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import generation_pb2 as openengine_dot_v1_dot_generation__pb2
from . import kv_pb2 as openengine_dot_v1_dot_kv__pb2
from . import lifecycle_pb2 as openengine_dot_v1_dot_lifecycle__pb2
from . import lora_pb2 as openengine_dot_v1_dot_lora__pb2
from . import model_pb2 as openengine_dot_v1_dot_model__pb2
from . import server_pb2 as openengine_dot_v1_dot_server__pb2

GRPC_GENERATED_VERSION = '1.64.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in openengine/v1/openengine_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class InferenceStub(object):
    """Standard ASCII gRPC request metadata:
    - openengine-routing-key: opaque application routing key.
    - openengine-target-dp-rank: base-10 uint32 routing target. This does not
    establish KV affinity; KvSessionRef.dp_rank is authoritative for a session.
    - openengine-priority: base-10 int32 admission priority; higher values have
    higher priority.
    - traceparent and tracestate: W3C Trace Context.

    The openengine- prefix is reserved for metadata defined by this protocol.
    Routing and admission keys apply to Inference RPCs. Trace Context applies to
    every RPC and should be propagated across downstream calls.

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Generate = channel.unary_stream(
                '/openengine.v1.Inference/Generate',
                request_serializer=openengine_dot_v1_dot_generation__pb2.GenerateRequest.SerializeToString,
                response_deserializer=openengine_dot_v1_dot_generation__pb2.GenerateResponse.FromString,
                _registered_method=True)


class InferenceServicer(object):
    """Standard ASCII gRPC request metadata:
    - openengine-routing-key: opaque application routing key.
    - openengine-target-dp-rank: base-10 uint32 routing target. This does not
    establish KV affinity; KvSessionRef.dp_rank is authoritative for a session.
    - openengine-priority: base-10 int32 admission priority; higher values have
    higher priority.
    - traceparent and tracestate: W3C Trace Context.

    The openengine- prefix is reserved for metadata defined by this protocol.
    Routing and admission keys apply to Inference RPCs. Trace Context applies to
    every RPC and should be propagated across downstream calls.

    """

    def Generate(self, request, context):
        """Core inference path.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InferenceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Generate': grpc.unary_stream_rpc_method_handler(
                    servicer.Generate,
                    request_deserializer=openengine_dot_v1_dot_generation__pb2.GenerateRequest.FromString,
                    response_serializer=openengine_dot_v1_dot_generation__pb2.GenerateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'openengine.v1.Inference', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('openengine.v1.Inference', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Inference(object):
    """Standard ASCII gRPC request metadata:
    - openengine-routing-key: opaque application routing key.
    - openengine-target-dp-rank: base-10 uint32 routing target. This does not
    establish KV affinity; KvSessionRef.dp_rank is authoritative for a session.
    - openengine-priority: base-10 int32 admission priority; higher values have
    higher priority.
    - traceparent and tracestate: W3C Trace Context.

    The openengine- prefix is reserved for metadata defined by this protocol.
    Routing and admission keys apply to Inference RPCs. Trace Context applies to
    every RPC and should be propagated across downstream calls.

    """

    @staticmethod
    def Generate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/openengine.v1.Inference/Generate',
            openengine_dot_v1_dot_generation__pb2.GenerateRequest.SerializeToString,
            openengine_dot_v1_dot_generation__pb2.GenerateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ControlStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetServerInfo = channel.unary_unary(
                '/openengine.v1.Control/GetServerInfo',
                request_serializer=openengine_dot_v1_dot_server__pb2.GetServerInfoRequest.SerializeToString,
                response_deserializer=openengine_dot_v1_dot_server__pb2.ServerInfo.FromString,
                _registered_method=True)
        self.GetModelInfo = channel.unary_unary(
                '/openengine.v1.Control/GetModelInfo',
                request_serializer=openengine_dot_v1_dot_model__pb2.GetModelInfoRequest.SerializeToString,
                response_deserializer=openengine_dot_v1_dot_model__pb2.ModelInfo.FromString,
                _registered_method=True)
        self.GetLoad = channel.unary_unary(
                '/openengine.v1.Control/GetLoad',
                request_serializer=openengine_dot_v1_dot_server__pb2.GetLoadRequest.SerializeToString,
                response_deserializer=openengine_dot_v1_dot_server__pb2.LoadInfo.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/openengine.v1.Control/Health',
                request_serializer=openengine_dot_v1_dot_lifecycle__pb2.HealthRequest.SerializeToString,
                response_deserializer=openengine_dot_v1_dot_lifecycle__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.Abort = channel.unary_unary(
                '/openengine.v1.Control/Abort',
                request_serializer=openengine_dot_v1_dot_lifecycle__pb2.AbortRequest.SerializeToString,
                response_deserializer=openengine_dot_v1_dot_lifecycle__pb2.AbortResponse.FromString,
                _registered_method=True)
        self.LoadLora = channel.unary_unary(
                '/openengine.v1.Control/LoadLora',
                request_serializer=openengine_dot_v1_dot_lora__pb2.LoadLoraRequest.SerializeToString,
                response_deserializer=openengine_dot_v1_dot_lora__pb2.LoadLoraResponse.FromString,
                _registered_method=True)
        self.UnloadLora = channel.unary_unary(
                '/openengine.v1.Control/UnloadLora',
                request_serializer=openengine_dot_v1_dot_lora__pb2.UnloadLoraRequest.SerializeToString,
                response_deserializer=openengine_dot_v1_dot_lora__pb2.UnloadLoraResponse.FromString,
                _registered_method=True)
        self.ListLoras = channel.unary_unary(
                '/openengine.v1.Control/ListLoras',
                request_serializer=openengine_dot_v1_dot_lora__pb2.ListLorasRequest.SerializeToString,
                response_deserializer=openengine_dot_v1_dot_lora__pb2.ListLorasResponse.FromString,
                _registered_method=True)
        self.GetKvEventSources = channel.unary_unary(
                '/openengine.v1.Control/GetKvEventSources',
                request_serializer=openengine_dot_v1_dot_kv__pb2.GetKvEventSourcesRequest.SerializeToString,
                response_deserializer=openengine_dot_v1_dot_kv__pb2.GetKvEventSourcesResponse.FromString,
                _registered_method=True)
        self.SubscribeKvEvents = channel.unary_stream(
                '/openengine.v1.Control/SubscribeKvEvents',
                request_serializer=openengine_dot_v1_dot_kv__pb2.SubscribeKvEventsRequest.SerializeToString,
                response_deserializer=openengine_dot_v1_dot_kv__pb2.SubscribeKvEventsResponse.FromString,
                _registered_method=True)


class ControlServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetServerInfo(self, request, context):
        """Runtime metadata and scheduling state.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetModelInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLoad(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Health and lifecycle.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Abort(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoadLora(self, request, context):
        """LoRA lifecycle.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnloadLora(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListLoras(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetKvEventSources(self, request, context):
        """Disaggregated serving / KV transfer. Connector info: ServerInfo.kv_connector.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeKvEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ControlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetServerInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetServerInfo,
                    request_deserializer=openengine_dot_v1_dot_server__pb2.GetServerInfoRequest.FromString,
                    response_serializer=openengine_dot_v1_dot_server__pb2.ServerInfo.SerializeToString,
            ),
            'GetModelInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetModelInfo,
                    request_deserializer=openengine_dot_v1_dot_model__pb2.GetModelInfoRequest.FromString,
                    response_serializer=openengine_dot_v1_dot_model__pb2.ModelInfo.SerializeToString,
            ),
            'GetLoad': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLoad,
                    request_deserializer=openengine_dot_v1_dot_server__pb2.GetLoadRequest.FromString,
                    response_serializer=openengine_dot_v1_dot_server__pb2.LoadInfo.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=openengine_dot_v1_dot_lifecycle__pb2.HealthRequest.FromString,
                    response_serializer=openengine_dot_v1_dot_lifecycle__pb2.HealthResponse.SerializeToString,
            ),
            'Abort': grpc.unary_unary_rpc_method_handler(
                    servicer.Abort,
                    request_deserializer=openengine_dot_v1_dot_lifecycle__pb2.AbortRequest.FromString,
                    response_serializer=openengine_dot_v1_dot_lifecycle__pb2.AbortResponse.SerializeToString,
            ),
            'LoadLora': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadLora,
                    request_deserializer=openengine_dot_v1_dot_lora__pb2.LoadLoraRequest.FromString,
                    response_serializer=openengine_dot_v1_dot_lora__pb2.LoadLoraResponse.SerializeToString,
            ),
            'UnloadLora': grpc.unary_unary_rpc_method_handler(
                    servicer.UnloadLora,
                    request_deserializer=openengine_dot_v1_dot_lora__pb2.UnloadLoraRequest.FromString,
                    response_serializer=openengine_dot_v1_dot_lora__pb2.UnloadLoraResponse.SerializeToString,
            ),
            'ListLoras': grpc.unary_unary_rpc_method_handler(
                    servicer.ListLoras,
                    request_deserializer=openengine_dot_v1_dot_lora__pb2.ListLorasRequest.FromString,
                    response_serializer=openengine_dot_v1_dot_lora__pb2.ListLorasResponse.SerializeToString,
            ),
            'GetKvEventSources': grpc.unary_unary_rpc_method_handler(
                    servicer.GetKvEventSources,
                    request_deserializer=openengine_dot_v1_dot_kv__pb2.GetKvEventSourcesRequest.FromString,
                    response_serializer=openengine_dot_v1_dot_kv__pb2.GetKvEventSourcesResponse.SerializeToString,
            ),
            'SubscribeKvEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeKvEvents,
                    request_deserializer=openengine_dot_v1_dot_kv__pb2.SubscribeKvEventsRequest.FromString,
                    response_serializer=openengine_dot_v1_dot_kv__pb2.SubscribeKvEventsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'openengine.v1.Control', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('openengine.v1.Control', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Control(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetServerInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/openengine.v1.Control/GetServerInfo',
            openengine_dot_v1_dot_server__pb2.GetServerInfoRequest.SerializeToString,
            openengine_dot_v1_dot_server__pb2.ServerInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetModelInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/openengine.v1.Control/GetModelInfo',
            openengine_dot_v1_dot_model__pb2.GetModelInfoRequest.SerializeToString,
            openengine_dot_v1_dot_model__pb2.ModelInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLoad(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/openengine.v1.Control/GetLoad',
            openengine_dot_v1_dot_server__pb2.GetLoadRequest.SerializeToString,
            openengine_dot_v1_dot_server__pb2.LoadInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/openengine.v1.Control/Health',
            openengine_dot_v1_dot_lifecycle__pb2.HealthRequest.SerializeToString,
            openengine_dot_v1_dot_lifecycle__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Abort(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/openengine.v1.Control/Abort',
            openengine_dot_v1_dot_lifecycle__pb2.AbortRequest.SerializeToString,
            openengine_dot_v1_dot_lifecycle__pb2.AbortResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LoadLora(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/openengine.v1.Control/LoadLora',
            openengine_dot_v1_dot_lora__pb2.LoadLoraRequest.SerializeToString,
            openengine_dot_v1_dot_lora__pb2.LoadLoraResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnloadLora(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/openengine.v1.Control/UnloadLora',
            openengine_dot_v1_dot_lora__pb2.UnloadLoraRequest.SerializeToString,
            openengine_dot_v1_dot_lora__pb2.UnloadLoraResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListLoras(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/openengine.v1.Control/ListLoras',
            openengine_dot_v1_dot_lora__pb2.ListLorasRequest.SerializeToString,
            openengine_dot_v1_dot_lora__pb2.ListLorasResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetKvEventSources(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/openengine.v1.Control/GetKvEventSources',
            openengine_dot_v1_dot_kv__pb2.GetKvEventSourcesRequest.SerializeToString,
            openengine_dot_v1_dot_kv__pb2.GetKvEventSourcesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeKvEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/openengine.v1.Control/SubscribeKvEvents',
            openengine_dot_v1_dot_kv__pb2.SubscribeKvEventsRequest.SerializeToString,
            openengine_dot_v1_dot_kv__pb2.SubscribeKvEventsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
