# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
"""Fused attention core with fully explicit state: paged KV-cache append + masked FMHA.

Wraps the pybind binding ``tensorrt_llm.bindings.internal.thop.attention``
(approved policy exception to the ``torch.ops.trtllm.*`` entry shape): the
same C++ attention op behind the TRTLLM backend, but every piece of batch
state and layer config arrives as an explicit argument — no registered
layers, no thread-local metadata.
"""

from typing import Optional

import torch

from tensorrt_llm.bindings.internal import thop


def thop_attention(
    q: torch.Tensor,
    k: Optional[torch.Tensor],
    v: Optional[torch.Tensor],
    output: torch.Tensor,
    output_sf: Optional[torch.Tensor],
    workspace_: Optional[torch.Tensor],
    sequence_length: torch.Tensor,
    host_past_key_value_lengths: torch.Tensor,
    host_total_kv_lens: torch.Tensor,
    context_lengths: torch.Tensor,
    host_context_lengths: torch.Tensor,
    host_request_types: torch.Tensor,
    max_context_q_len_override: Optional[int],
    kv_cache_block_offsets: Optional[torch.Tensor],
    host_kv_cache_pool_pointers: Optional[torch.Tensor],
    host_kv_cache_pool_mapping: Optional[torch.Tensor],
    cache_indirection: Optional[torch.Tensor],
    kv_scale_orig_quant: Optional[torch.Tensor],
    kv_scale_quant_orig: Optional[torch.Tensor],
    out_scale: Optional[torch.Tensor],
    rotary_inv_freq: Optional[torch.Tensor],
    rotary_cos_sin: Optional[torch.Tensor],
    latent_cache: Optional[torch.Tensor],
    q_pe: Optional[torch.Tensor],
    block_ids_per_seq: Optional[torch.Tensor],
    attention_sinks: Optional[torch.Tensor],
    is_fused_qkv: bool,
    update_kv_cache: bool,
    predicted_tokens_per_seq: int,
    local_layer_idx: int,
    num_heads: int,
    num_kv_heads: int,
    head_size: int,
    tokens_per_block: Optional[int],
    max_num_requests: int,
    max_context_length: int,
    max_seq_len: int,
    attention_window_size: int,
    beam_width: int,
    mask_type: int,
    quant_mode: int,
    q_scaling: float,
    position_embedding_type: int,
    rope_dim: int,
    rope_base: float,
    rope_scale_type: int,
    rope_scale: float,
    rope_short_m_scale: float,
    rope_long_m_scale: float,
    rope_max_positions: int,
    rope_original_max_positions: int,
    use_paged_context_fmha: bool,
    attention_input_type: Optional[int],
    is_mla_enable: bool,
    chunked_prefill_buffer_batch_size: Optional[int],
    q_lora_rank: Optional[int],
    kv_lora_rank: Optional[int],
    qk_nope_head_dim: Optional[int],
    qk_rope_head_dim: Optional[int],
    v_head_dim: Optional[int],
    rope_append: Optional[bool],
    mrope_rotary_cos_sin: Optional[torch.Tensor],
    mrope_position_deltas: Optional[torch.Tensor],
    helix_position_offsets: Optional[torch.Tensor],
    helix_is_inactive_rank: Optional[torch.Tensor],
    attention_chunk_size: Optional[int],
    softmax_stats_tensor: Optional[torch.Tensor],
    is_spec_decoding_enabled: bool,
    use_spec_decoding: bool,
    is_spec_dec_tree: bool,
    spec_decoding_generation_lengths: Optional[torch.Tensor],
    spec_decoding_position_offsets_for_cpp: Optional[torch.Tensor],
    spec_decoding_packed_mask: Optional[torch.Tensor],
    spec_decoding_bl_tree_mask_offset: Optional[torch.Tensor],
    spec_decoding_bl_tree_mask: Optional[torch.Tensor],
    spec_bl_tree_first_sparse_mask_offset_kv: Optional[torch.Tensor],
    sparse_kv_indices: Optional[torch.Tensor],
    sparse_kv_offsets: Optional[torch.Tensor],
    sparse_attn_indices: Optional[torch.Tensor],
    sparse_attn_offsets: Optional[torch.Tensor],
    sparse_attn_indices_block_size: int,
    num_sparse_topk: Optional[int] = None,
    sparse_attn_kv_lens: Optional[torch.Tensor] = None,
    skip_softmax_threshold_scale_factor_prefill: Optional[float] = None,
    skip_softmax_threshold_scale_factor_decode: Optional[float] = None,
    skip_softmax_stat: Optional[torch.Tensor] = None,
    cu_q_seqlens: Optional[torch.Tensor] = None,
    cu_kv_seqlens: Optional[torch.Tensor] = None,
    fmha_scheduler_counter: Optional[torch.Tensor] = None,
    mla_bmm1_scale: Optional[torch.Tensor] = None,
    mla_bmm2_scale: Optional[torch.Tensor] = None,
    quant_q_buffer: Optional[torch.Tensor] = None,
    flash_mla_tile_scheduler_metadata: Optional[torch.Tensor] = None,
    flash_mla_num_splits: Optional[torch.Tensor] = None,
    sage_attn_num_elts_per_blk_q: int = 0,
    sage_attn_num_elts_per_blk_k: int = 0,
    sage_attn_num_elts_per_blk_v: int = 0,
    sage_attn_qk_int8: bool = False,
    num_contexts: int = 0,
    num_ctx_tokens: int = 0,
    trtllm_gen_jit_warmup: bool = False,
    aux_kv_cache_pool_ptr: Optional[int] = None,
    is_cross: bool = False,
    cross_kv: Optional[torch.Tensor] = None,
    relative_attention_bias: Optional[torch.Tensor] = None,
    relative_attention_max_distance: int = 0,
    spec_decoding_target_max_draft_tokens: Optional[int] = None,
    quant_scale_qkv: Optional[torch.Tensor] = None,
    dsv4_inv_rope_cos_sin_cache: Optional[torch.Tensor] = None,
    enable_dsv4_epilogue_fusion: bool = False,
    # Added between 1.3.0rc21 and 1.3.0rc26. Defaults reproduce the behaviour
    # the op had before they existed, and match what the in-tree caller
    # (attention/backends/fmha/fallback.py) passes on a dense, non-sparse,
    # non-folded path -- which is the path both migrated targets are on.
    max_num_sequences: Optional[int] = None,
    force_prepare_spec_dec_tree_mask: bool = False,
    kv_norm_weight: Optional[torch.Tensor] = None,
    kv_norm_eps: float = 1e-6,
    skip_correction_threshold: float = 0.0,
) -> None:
    """Run the fused attention core over one prepared batch — paged KV-cache
    append + masked FMHA (standard), or the MLA context/generation phase
    selected by attention_input_type; writes rows [:num_tokens] of output.
    Returns None."""
    # num_heads must be an integer multiple of num_kv_heads. A context-only
    # call with a non-multiple returns without raising on sm_100 (observed at
    # 6q/4kv d128: only the first (num_heads // num_kv_heads) * num_kv_heads
    # head columns of output are computed, the rest come back all-zero), so
    # the geometry cannot be left for the op to reject.
    assert num_heads % num_kv_heads == 0, (
        f"num_heads ({num_heads}) must be a multiple of num_kv_heads ({num_kv_heads})"
    )
    # attention_sinks is consumed as a raw buffer of exactly num_heads fp32
    # values read from data_ptr(); only its dtype is validated by the op. On
    # sm_100 a stride-2 view whose values were correct produced silently wrong
    # output (the underlying memory is what gets read), a 32-element tensor was
    # read 64 elements deep past its end, a 128-element one had its tail
    # silently ignored, and an empty tensor silently disabled the sink.
    if attention_sinks is not None:
        assert attention_sinks.is_contiguous() and attention_sinks.numel() == num_heads, (
            f"attention_sinks must be contiguous with exactly num_heads "
            f"({num_heads}) elements, got shape "
            f"{tuple(attention_sinks.shape)} contiguous="
            f"{attention_sinks.is_contiguous()}"
        )
    thop.attention(
        q=q,
        k=k,
        v=v,
        output=output,
        output_sf=output_sf,
        workspace_=workspace_,
        sequence_length=sequence_length,
        host_past_key_value_lengths=host_past_key_value_lengths,
        host_total_kv_lens=host_total_kv_lens,
        context_lengths=context_lengths,
        host_context_lengths=host_context_lengths,
        host_request_types=host_request_types,
        max_context_q_len_override=max_context_q_len_override,
        kv_cache_block_offsets=kv_cache_block_offsets,
        host_kv_cache_pool_pointers=host_kv_cache_pool_pointers,
        host_kv_cache_pool_mapping=host_kv_cache_pool_mapping,
        cache_indirection=cache_indirection,
        kv_scale_orig_quant=kv_scale_orig_quant,
        kv_scale_quant_orig=kv_scale_quant_orig,
        out_scale=out_scale,
        rotary_inv_freq=rotary_inv_freq,
        rotary_cos_sin=rotary_cos_sin,
        latent_cache=latent_cache,
        q_pe=q_pe,
        block_ids_per_seq=block_ids_per_seq,
        attention_sinks=attention_sinks,
        is_fused_qkv=is_fused_qkv,
        update_kv_cache=update_kv_cache,
        predicted_tokens_per_seq=predicted_tokens_per_seq,
        local_layer_idx=local_layer_idx,
        num_heads=num_heads,
        num_kv_heads=num_kv_heads,
        head_size=head_size,
        tokens_per_block=tokens_per_block,
        max_num_requests=max_num_requests,
        max_context_length=max_context_length,
        max_seq_len=max_seq_len,
        attention_window_size=attention_window_size,
        beam_width=beam_width,
        mask_type=mask_type,
        quant_mode=quant_mode,
        q_scaling=q_scaling,
        position_embedding_type=position_embedding_type,
        rope_dim=rope_dim,
        rope_base=rope_base,
        rope_scale_type=rope_scale_type,
        rope_scale=rope_scale,
        rope_short_m_scale=rope_short_m_scale,
        rope_long_m_scale=rope_long_m_scale,
        rope_max_positions=rope_max_positions,
        rope_original_max_positions=rope_original_max_positions,
        use_paged_context_fmha=use_paged_context_fmha,
        attention_input_type=attention_input_type,
        is_mla_enable=is_mla_enable,
        chunked_prefill_buffer_batch_size=chunked_prefill_buffer_batch_size,
        q_lora_rank=q_lora_rank,
        kv_lora_rank=kv_lora_rank,
        qk_nope_head_dim=qk_nope_head_dim,
        qk_rope_head_dim=qk_rope_head_dim,
        v_head_dim=v_head_dim,
        rope_append=rope_append,
        mrope_rotary_cos_sin=mrope_rotary_cos_sin,
        mrope_position_deltas=mrope_position_deltas,
        helix_position_offsets=helix_position_offsets,
        helix_is_inactive_rank=helix_is_inactive_rank,
        attention_chunk_size=attention_chunk_size,
        softmax_stats_tensor=softmax_stats_tensor,
        is_spec_decoding_enabled=is_spec_decoding_enabled,
        use_spec_decoding=use_spec_decoding,
        is_spec_dec_tree=is_spec_dec_tree,
        spec_decoding_generation_lengths=spec_decoding_generation_lengths,
        spec_decoding_position_offsets_for_cpp=spec_decoding_position_offsets_for_cpp,
        spec_decoding_packed_mask=spec_decoding_packed_mask,
        spec_decoding_bl_tree_mask_offset=spec_decoding_bl_tree_mask_offset,
        spec_decoding_bl_tree_mask=spec_decoding_bl_tree_mask,
        spec_bl_tree_first_sparse_mask_offset_kv=spec_bl_tree_first_sparse_mask_offset_kv,
        sparse_kv_indices=sparse_kv_indices,
        sparse_kv_offsets=sparse_kv_offsets,
        sparse_attn_indices=sparse_attn_indices,
        sparse_attn_offsets=sparse_attn_offsets,
        sparse_attn_indices_block_size=sparse_attn_indices_block_size,
        num_sparse_topk=num_sparse_topk,
        sparse_attn_kv_lens=sparse_attn_kv_lens,
        skip_softmax_threshold_scale_factor_prefill=skip_softmax_threshold_scale_factor_prefill,
        skip_softmax_threshold_scale_factor_decode=skip_softmax_threshold_scale_factor_decode,
        skip_softmax_stat=skip_softmax_stat,
        cu_q_seqlens=cu_q_seqlens,
        cu_kv_seqlens=cu_kv_seqlens,
        fmha_scheduler_counter=fmha_scheduler_counter,
        mla_bmm1_scale=mla_bmm1_scale,
        mla_bmm2_scale=mla_bmm2_scale,
        quant_q_buffer=quant_q_buffer,
        flash_mla_tile_scheduler_metadata=flash_mla_tile_scheduler_metadata,
        flash_mla_num_splits=flash_mla_num_splits,
        sage_attn_num_elts_per_blk_q=sage_attn_num_elts_per_blk_q,
        sage_attn_num_elts_per_blk_k=sage_attn_num_elts_per_blk_k,
        sage_attn_num_elts_per_blk_v=sage_attn_num_elts_per_blk_v,
        sage_attn_qk_int8=sage_attn_qk_int8,
        num_contexts=num_contexts,
        num_ctx_tokens=num_ctx_tokens,
        trtllm_gen_jit_warmup=trtllm_gen_jit_warmup,
        aux_kv_cache_pool_ptr=aux_kv_cache_pool_ptr,
        is_cross=is_cross,
        cross_kv=cross_kv,
        relative_attention_bias=relative_attention_bias,
        relative_attention_max_distance=relative_attention_max_distance,
        spec_decoding_target_max_draft_tokens=spec_decoding_target_max_draft_tokens,
        quant_scale_qkv=quant_scale_qkv,
        dsv4_inv_rope_cos_sin_cache=dsv4_inv_rope_cos_sin_cache,
        enable_dsv4_epilogue_fusion=enable_dsv4_epilogue_fusion,
        max_num_sequences=max_num_sequences,
        force_prepare_spec_dec_tree_mask=force_prepare_spec_dec_tree_mask,
        kv_norm_weight=kv_norm_weight,
        kv_norm_eps=kv_norm_eps,
        skip_correction_threshold=skip_correction_threshold,
    )
