world_size: 2
transforms:
  detect_sharding:
    enabled: false
  sharding_transform_executor:
    enabled: false
  apply_sharding_hints:
    enabled: true
    requires_shape_prop: true
    shard_layers: ["mha", "moe"]
    dist_mapping:
      tp: 2
      moe_tp: 2
      moe_ep: 1
