# dtype is missing from config for this model, so we provide it explicitly.
cuda_graph_config:
  max_batch_size: 16
kv_cache_config:
  free_gpu_memory_fraction: 0.5
model_kwargs:
  torch_dtype: bfloat16
