compile_backend: torch-cudagraph
enable_chunked_prefill: true
model_factory: AutoModelForCausalLM
runtime: trtllm
kv_cache_config:
  dtype: fp8
  free_gpu_memory_fraction: 0.9
attn_backend: trtllm
max_batch_size: 256
max_seq_len: 16384
transforms:
  detect_sharding:
    allreduce_strategy: SYMM_MEM
    sharding_source: ['manual']
    manual_config:
      head_dim: 128
      tp_plan:
        "q_proj": "colwise"
        "k_proj": "colwise"
        "v_proj": "colwise"
        "o_proj": "rowwise"
        "gate_proj": "colwise"
        "up_proj": "colwise"
        "down_proj": "rowwise"
  fuse_trtllm_attn_quant_fp8:
    enabled: true
  fuse_fp8_gemms:
    enabled: true
  fuse_rmsnorm_quant_fp8:
    enabled: true
  fuse_gemms_mixed_children:
    enabled: true
  fuse_rope_into_trtllm_attention:
    enabled: true
  fuse_silu_mul:
    enabled: true
    backend: trtllm
  compile_model:
    piecewise_enabled: true
  mlir_elementwise_fusion:
    stage: post_load_fusion
    enabled: true
    run_shape_prop: false
    bypass_ops: []
