max_batch_size: 384
max_seq_len: 65536 # tunable
enable_chunked_prefill: true
cuda_graph_config:
  batch_sizes: [1, 2, 4, 8, 16, 24, 32, 64, 128, 256, 320, 384]
kv_cache_config:
  free_gpu_memory_fraction: 0.88
