# Configuration for Nemotron-3-Super-120B v3
max_batch_size: 384
max_seq_len: 65536 # tunable
enable_chunked_prefill: true
cuda_graph_config:
  batch_sizes: [1, 2, 4, 8, 16, 24, 32, 64, 128, 256, 320, 384]
kv_cache_config:
  # tunable mamba cache dtype
  # --> use float32 for accuracy and default (auto) for speed
  mamba_ssm_cache_dtype: auto
