# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

runtime: trtllm
compile_backend: torch-cudagraph
max_batch_size: 128
max_seq_len: 65536
max_num_tokens: 8192
enable_chunked_prefill: true
attn_backend: trtllm
enable_attention_dp: false
model_factory: AutoModelForCausalLM
stream_interval: 10
cuda_graph_config:
  batch_sizes: [1, 2, 4, 8, 16, 32, 64, 128]
kv_cache_config:
  dtype: fp8
  enable_block_reuse: false
  free_gpu_memory_fraction: 0.8
  mamba_ssm_cache_dtype: float16
  mamba_ssm_philox_rounds: 5
  mamba_ssm_stochastic_rounding: true
transforms:
  detect_sharding:
    enable_attention_dp: false
    allreduce_strategy: SYMM_MEM
    sharding_dims: [ep, bmm, tp]
    sharding_source: [manual]
    manual_config:
      head_dim: 128
      tp_plan:
        in_proj: mamba
        out_proj: rowwise
        q_proj: colwise
        k_proj: colwise
        v_proj: colwise
        o_proj: rowwise
        up_proj: colwise
        down_proj: rowwise
        fc1_latent_proj: gather
        fc2_latent_proj: gather
  gather_logits_before_lm_head:
    enabled: true
  multi_stream_moe:
    stage: compile
    enabled: false
  fuse_mamba_a_log:
    stage: post_load_fusion
    enabled: true
  insert_cached_ssm_attention:
    backend: triton_ssm
  fuse_fp8_moe:
    allow_different_input_scales: true
  fuse_nvfp4_moe:
    backend: trtllm_gen
    allow_different_input_scales: true
    use_internal_routing: true
  fuse_trtllm_attn_quant_fp8:
    enabled: true
  fuse_rmsnorm_quant_fp8:
    enabled: true
  fuse_gemms_mixed_children:
    enabled: true
  multi_stream_gemm:
    enabled: true
  compile_model:
    piecewise_enabled: false
  fuse_rmsnorm_quant_nvfp4:
    enabled: true
  mlir_elementwise_fusion:
    enabled: true
  load_weights:
    disable_preload: false
