[tool.poetry]
name = "unknown-package"
version = "0.1.0"
description = ""
authors = ["TensorRT LLM [svc_tensorrt_llm@nvidia.com]"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
transformers = ">=4.47.1"
diffusers = ">=0.32.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
