# NOTE: Although the Java Properties file format is more flexible, cf.
#     https://docs.oracle.com/cd/E23095_01/Platform.93/ATGProgGuide/html/s0204propertiesfileformat01.html
#   keep the format compatible with
#     https://code.visualstudio.com/remote/advancedcontainers/environment-variables#_option-2-use-an-env-file
#   for reuse in Dev Containers configuration.
LLM_DOCKER_IMAGE_URI=urm.nvidia.com/sw-tensorrt-docker/tensorrt-llm
LLM_DOCKER_IMAGE_X86_TAG_SUFFIX=pytorch-25.05-py3-x86_64-ubuntu24.04
LLM_DOCKER_IMAGE_TAG_SUFFIX=-trt10.11.0.33-skip-tritondevel-202506051650-4885
