# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""Discrete MoE guards whose CASE LIST comes from a layer-wise nsys trace.

The split this file exists to enforce: the trace decides WHAT is worth guarding,
this file decides HOW to guard it. ``v4_trace_cases.json`` is generated by
``tools/gen_module_cases.py`` from a real DeepSeek-V4 layer-wise run and is
regenerated, never hand-edited; the assertions live here where they get reviewed.

Discrete only, on purpose. These tests answer "is the same implementation still
being selected", not "how fast is it". Timing is layer-wise benchmarking's job:
it runs the real 4-GPU module with replayed routing, and on the traced build it
tracked the expert GEMM to within 1.5%. Re-measuring that here on one GPU with
synthetic inputs would be a worse copy of a number we already have. What one GPU
CAN do is run per-commit in seconds, which is where a silent backend fallback or
a lost fusion gets caught a day earlier.

Deliberately NOT covered: ``moeA2A*``. Those need a real EP group
(``mapping.py`` forces ``moe_ep * moe_tp == world_size``), and their measured
duration is mostly waiting for peers anyway -- layer-wise under-reports them by
60-73% and a single GPU cannot produce them at all. They are an e2e-only signal;
see the coverage report rather than assuming this file covers them.

Run:
    pytest tests/microbenchmarks/bench_moe/test_v4_trace_discrete.py -m discrete -v
"""

from __future__ import annotations

import json
import re
from pathlib import Path

import pytest
import torch

# Positions in deep_gemm::sm100_fp8_fp4_gemm_1d1d_impl's template list, from the
# pinned upstream header (3rdparty/fetch_content.json -> deepgemm f8e8fb58,
# deep_gemm/include/deep_gemm/impls/sm100_fp8_fp4_gemm_1d1d.cuh:16). Zero-based:
#   0 kMajorA  1 kMajorB  2 kGranKA  3 kGranKB  4 kKAlignment
#   5 SHAPE_M  6 SHAPE_N  7 SHAPE_K  8 BLOCK_M  9 BLOCK_N  10 BLOCK_K
#   11 kNumGroups  ... 25 a_dtype  26 b_dtype  27 cd_dtype  28 epilogue
_DG_ARITY, _DG_N, _DG_K, _DG_GROUPS = 29, 6, 7, 11

_MANIFEST_PATH = Path(__file__).parent / "v4_trace_cases.json"

_GPU = pytest.mark.skipif(not torch.cuda.is_available(), reason="requires a GPU")

# Golden launch counts, keyed by (case_id, sm_arch), same protocol as
# test_discrete_metrics.py: an absent key makes the test print what it observed
# and SKIP, so a new arch bootstraps instead of false-firing. Pinning a value is
# an explicit, reviewed decision -- confirm zero variance over K runs first.
#
#   sm100 (B200, cluster): 11 kernels, 3/3 zero variance across independent
#   container runs (builds #45, #47, #48) on wheel 1.3.0rc24 / 20260811100855_9f1eb3a6.
#   Build #44 observed 0 on the same config and is NOT a fourth sample -- that
#   was a broken CUPTI capture, which now fails loudly instead of looking like a
#   bootstrap. Do not pin a count of 0; it would assert nothing and stay green.
_EXPECTED_LAUNCH_COUNT: dict[str, dict[str, int]] = {
    "deepgemm_e64_h4096_i2048_t128": {"sm100": 11},
}


def _split_template_args(s: str) -> list[str]:
    """Split a template argument list on commas that are not nested."""
    out, depth, cur = [], 0, []
    for ch in s:
        if ch in "<([":
            depth += 1
        elif ch in ">)]":
            depth -= 1
        if ch == "," and depth == 0:
            out.append("".join(cur).strip())
            cur = []
        else:
            cur.append(ch)
    if cur:
        out.append("".join(cur).strip())
    return out


def _deep_gemm_shape(demangled: str):
    """(N, K, num_groups) for one deep_gemm instantiation, or None.

    Matching on formatted substrings does not work: the two demanglers in play
    print the same value differently. nsys writes ``(unsigned int)4096`` while
    cxxfilt -- what the CUPTI path uses -- writes ``4096u``, so a needle built
    from one format silently fails to find a kernel that is right there. Build
    #45 failed exactly that way, reporting the two dominant GEMMs as absent
    while printing them in the very same message. Parse positionally and compare
    numbers instead.

    Returns None when the arity does not match the pinned header, because a
    changed parameter list shifts every position after it and a best-effort read
    would compare the wrong fields.
    """
    m = re.search(r"deep_gemm::sm100_fp8_fp4_gemm_1d1d_impl<(.*)>\s*\(", demangled, re.S)
    if not m:
        return None
    args = _split_template_args(m.group(1))
    if len(args) != _DG_ARITY:
        return None

    def _int(a):
        v = re.sub(r"^\((?:unsigned )?int\)\s*", "", a.strip())  # nsys form
        v = re.sub(r"[uU]+$", "", v.strip())  # cxxfilt form
        return int(v) if re.fullmatch(r"-?\d+", v) else None

    n, k, g = _int(args[_DG_N]), _int(args[_DG_K]), _int(args[_DG_GROUPS])
    return None if None in (n, k, g) else (n, k, g)


def _current_sm() -> str:
    major, minor = torch.cuda.get_device_capability()
    return f"sm{major}{minor}"


def _manifest() -> dict:
    if not _MANIFEST_PATH.exists():
        pytest.skip(
            f"{_MANIFEST_PATH.name} absent; run tools/gen_module_cases.py "
            "against a layer-wise artifact directory to generate it"
        )
    m = json.loads(_MANIFEST_PATH.read_text(encoding="utf-8"))
    dims = m.get("derived_dims")
    if not dims or not dims.get("consistent"):
        pytest.skip(
            "manifest carries no self-consistent hidden/intermediate pair "
            f"({dims}); the traced shapes are not the gate-up/down pair this "
            "file assumes, so building a module from them would guard the wrong "
            "thing. Regenerate, or extend gen_module_cases.py for this layout."
        )
    if not m.get("experts_per_rank"):
        pytest.skip("manifest has no grouped GEMM, so no experts-per-rank to mirror")
    return m


def _case_id(m: dict) -> str:
    w, d = m["case_inputs"], m["derived_dims"]
    return (
        f"{w['moe_backend'].lower()}_e{m['experts_per_rank']}"
        f"_h{d['hidden_size']}_i{d['intermediate_size']}_t{w['num_tokens']}"
    )


def _build_traced_moe(m: dict):
    """One-GPU stand-in for one rank of the traced EP group.

    ``mapping.py:83`` requires ``moe_ep_size * moe_tp_size == world_size``, so a
    single process cannot be EP4. It does not need to be: the grouped GEMM only
    sees *this rank's* expert count, and num_groups in the trace IS that count
    (256 experts over EP4 -> 64). Declaring num_experts = experts_per_rank on one
    GPU reproduces the same per-rank GEMM shape. This is the same substitution
    the layer-wise runner makes for ``--scaled-from`` (runner.py:463), which
    rewrites n_routed_experts to hold per-rank width constant while changing the
    GPU count.

    What this does NOT reproduce is the all-to-all, which is why nothing here
    asserts on it.
    """
    from tensorrt_llm.mapping import Mapping

    from .build import _build_moe_module
    from .specs import BUILT_IN_MODELS, ConfigSpec, ModelSpec

    w, d = m["case_inputs"], m["derived_dims"]
    # top_k and the routing method are model properties that a kernel-name trace
    # cannot carry, so they come from the checked-in spec for the same model.
    ref = BUILT_IN_MODELS.get("deepseek_v4_flash")
    if ref is None:
        pytest.skip("BUILT_IN_MODELS has no deepseek_v4_flash to take top_k/routing from")

    model = ModelSpec(
        name="custom",
        num_experts=m["experts_per_rank"],
        top_k=ref.top_k,
        hidden_size=d["hidden_size"],
        intermediate_size=d["intermediate_size"],
        quant_algo="FP8_BLOCK_SCALES",  # the trace shows fp8_e4m3 in -> bf16 out
        routing_method=ref.routing_method,
    )
    config = ConfigSpec(
        backend=w["moe_backend"],
        parallel_mode="DEP",
        moe_ep_size=1,
        moe_tp_size=1,
        enable_attention_dp=False,
        comm_method="AUTO",
        cuda_graph=w["use_cuda_graph"],
    )
    mapping = Mapping(world_size=1, rank=0, moe_ep_size=1, moe_tp_size=1)

    moe, routing_logits_dtype = _build_moe_module(
        model=model,
        config=config,
        mapping=mapping,
        moe_backend=w["moe_backend"],
        use_cuda_graph=w["use_cuda_graph"],
        max_num_tokens=w["num_tokens"],
        use_low_precision_moe_combine=False,
        enable_perfect_router=False,
        dtype=torch.bfloat16,
        routing_logits_dtype=torch.float32,
        device=torch.device("cuda"),
    )
    return moe, model, routing_logits_dtype


@pytest.fixture(scope="module", autouse=True)
def _cupti_before_any_cuda_context():
    """Register CUPTI before the first test builds anything on the GPU.

    cupti.py:117 needs exactly 2*iters CUDA_EVENT records and returns None
    otherwise, which collapses the whole breakdown to empty lists. Its own
    diagnostic names the cause: "Most likely CUPTI was registered after CUDA
    context creation." That is what happened on build #44 -- the backend test
    runs first, builds a module on cuda, and by the time a later test called
    _try_init_cupti the context already existed, so both kernel-level tests saw
    0 kernels. Doing it here, once, before any test body, keeps the ordering
    right no matter which tests get selected.
    """
    if not torch.cuda.is_available():
        yield None
        return
    from .timing.cupti import _try_init_cupti

    yield _try_init_cupti()


def _forward_kernels(request, moe, model, routing_logits_dtype, num_tokens: int):
    from .timing.cuda_graph import _time_moe_forward_cuda_graph

    cupti_ctx = request.getfixturevalue("_cupti_before_any_cuda_context")
    if cupti_ctx is None or not cupti_ctx.ok:
        pytest.skip("cupti package unavailable; per-kernel breakdown not possible")

    x = torch.randn(num_tokens, model.hidden_size, dtype=torch.bfloat16, device="cuda")
    router_logits = torch.randn(
        num_tokens, model.num_experts, dtype=routing_logits_dtype, device="cuda"
    )
    _times, stats = _time_moe_forward_cuda_graph(
        moe,
        x,
        router_logits,
        all_rank_num_tokens=[num_tokens],
        warmup=3,
        iters=1,
        cupti_ctx=cupti_ctx,
        flush_l2=True,
    )
    kernels = stats.get("moe_forward_kernels") or []
    if not kernels:
        # Not a bootstrap condition. An empty breakdown means the capture itself
        # failed, and treating it as "observed 0" would invite pinning a golden of
        # 0 -- a test that asserts nothing while looking green forever. cupti.py
        # prints the reason to stdout, which pytest swallows on a passing or
        # skipped test, so `-s` is where to look.
        other = len(stats.get("other_kernels") or [])
        pytest.fail(
            "CUPTI captured no kernels inside the MoE forward window "
            f"({other} landed outside it). This is a broken capture, not a missing "
            "golden. cupti.py returns None when it does not see exactly 2*iters "
            "CUDA_EVENT records, usually because CUPTI was registered after the "
            "CUDA context existed; re-run with -s to see its diagnostic."
        )
    return kernels


@_GPU
@pytest.mark.discrete
def test_v4_moe_backend_honored():
    """The backend the traced run used is still the one that gets built.

    A silent downgrade (DeepGEMM absent -> generic path) shows up end-to-end only
    as "a few percent slower", which is inside e2e run-to-run noise. Here it is a
    string comparison.
    """
    from .build import _backend_name_from_module

    m = _manifest()
    want = m["case_inputs"]["moe_backend"]
    moe, _model, _rl = _build_traced_moe(m)
    got = _backend_name_from_module(moe)
    assert got == want, (
        f"traced run used MoE backend {want!r}; this build silently produced "
        f"{got!r} for the same shape (fallback regression)."
    )


@_GPU
@pytest.mark.discrete
def test_v4_moe_traced_gemm_shapes_present(request):
    """Every GEMM shape the trace says dominates the iteration is still issued.

    This is the assertion the trace buys. The shapes are compile-time template
    arguments, so a kernel with a different N/K/num_groups is a different
    instantiation and its absence means the dispatch chose something else --
    a different tile, a different backend, or a fused replacement. Any of those
    may be intentional; none should pass silently.

    Only num_groups/N/K are checked. SHAPE_M is 0 in these instantiations, which
    is DeepGEMM's sentinel for "M is a runtime argument", so the token dimension
    is not in the name and cannot be asserted from it.
    """
    m = _manifest()
    moe, model, rl = _build_traced_moe(m)
    kernels = _forward_kernels(request, moe, model, rl, m["case_inputs"]["num_tokens"])
    observed = {s for s in (_deep_gemm_shape(k["name"]) for k in kernels) if s}

    # Only the grouped shapes: the num_groups=1 ones come from the dense
    # GatedMLP branch, which this single-expert-group build does not exercise.
    wanted = [g for g in m["gemm_shapes"] if g["num_groups"] > 1]
    missing = [g for g in wanted if (g["N"], g["K"], g["num_groups"]) not in observed]

    assert not missing, (
        "GEMM shapes present in the traced run are absent from this build: "
        + ", ".join(
            f"N={g['N']} K={g['K']} groups={g['num_groups']} "
            f"({g['share_of_iteration'] * 100:.1f}% of a traced iteration)"
            for g in missing
        )
        + "\nobserved deep_gemm shapes (N, K, groups): "
        + (", ".join(str(s) for s in sorted(observed)) or "none")
        + "\nall kernels:\n"
        + "\n".join(k["name"] for k in kernels)
    )


@_GPU
@pytest.mark.discrete
def test_v4_moe_launch_count(request):
    """One MoE forward issues a fixed number of kernels.

    Catches lost fusion and lost graph coverage, both of which change the count
    without changing any single kernel's name.
    """
    m = _manifest()
    moe, model, rl = _build_traced_moe(m)
    observed = len(_forward_kernels(request, moe, model, rl, m["case_inputs"]["num_tokens"]))

    case_id, sm = _case_id(m), _current_sm()
    expected = _EXPECTED_LAUNCH_COUNT.get(case_id, {}).get(sm)
    if expected is None:
        pytest.skip(
            f"No golden pinned for {case_id!r} on {sm}. Observed {observed} kernels. "
            f"Confirm zero variance over K runs, then pin "
            f"_EXPECTED_LAUNCH_COUNT[{case_id!r}][{sm!r}] = {observed} to gate."
        )
    assert observed == expected, (
        f"MoE forward launch count changed for {case_id} on {sm}: observed "
        f"{observed}, golden {expected}. Update the golden in the same PR if the "
        f"change is intentional; otherwise this is a fusion or graph regression."
    )
