#!/bin/bash
set -e

task_with_command="${@:1}"
native_mpi_rank=$OMPI_COMM_WORLD_RANK
mpi_rank=${SLURM_PROCID:-${OMPI_COMM_WORLD_RANK:-${PMI_RANK:-${PMI_ID:-0}}}}

log_stderr() { echo -e "\033[33m$@\033[0m" >&2; }
log_stderr "mpi_rank: $mpi_rank"

pid=$(ps -o pid= -p $$ | tr -d ' ')

# A file to share the IPC address between the server and client
export TLLM_SPAWN_PROXY_PROCESS_ADDR_FILE=/tmp/llmapi-proxy-addr-${pid}
rm -f $TLLM_SPAWN_PROXY_PROCESS_ADDR_FILE

function mpi_world_size {
    if [ -n "$SLURM_NTASKS" ]; then
        echo "$SLURM_NTASKS"
    elif [ -n "$OMPI_COMM_WORLD_SIZE" ]; then
        echo "$OMPI_COMM_WORLD_SIZE"
    else
        echo "1"
    fi
}

export tllm_mpi_size=$(mpi_world_size)
log_stderr "tllm_mpi_size: $tllm_mpi_size"

if [ -z "$mpi_rank" ] || [ "$mpi_rank" -eq 0 ]; then
    log_stderr "rank${mpi_rank} run ${task_with_command} in background"

    # MPI doesn't allow spawn a process sharing the MPI environment in a MPI
    # process, or duplicate MPI_Init in the child process will cause undefined
    # behavior. Thus we need to clean the MPI environment in the parent process
    # before spawning the child process, and restore the MPI environment later
    # before running MPI operations in the parent process.
    mpi_blacklist=(
        OMPI_ PMIX_ PMI_ SLURM_ MPI_ UCX_
        I_MPI_ HYDRA_ KMP_ MPICH_ MV2_ CRAY_
    )

    (
        # Remove MPI-related variables only in the subshell context
        for var in $(compgen -e); do
            for prefix in "${mpi_blacklist[@]}"; do
                if [[ "$var" == "$prefix"* ]]; then
                    unset "$var"
                    break
                fi
            done
        done

        # Execute the task with cleaned environment
        $task_with_command
    ) &

    # Wait for the proxy process to write the IPC address to the file
    wait_timeout=120 # 2 minutes
    while [ ! -f $TLLM_SPAWN_PROXY_PROCESS_ADDR_FILE ]; do
        sleep 1
        wait_timeout=$((wait_timeout - 1))
        if [ $wait_timeout -le 0 ]; then
            log_stderr "rank${mpi_rank} wait for proxy process to write the IPC address to the file timeout"
            exit 1
        fi
    done

    log_stderr "rank${mpi_rank} run mgmn leader node with mpi_world_size: $(mpi_world_size) ..."
    log_stderr "rank0 host: $HOSTNAME"
    python3 -m tensorrt_llm.llmapi.mgmn_leader_node

    rm -f $TLLM_SPAWN_PROXY_PROCESS_ADDR_FILE # cleanup the file
else
    log_stderr "rank${mpi_rank} run mgmn worker node with mpi_world_size: $(mpi_world_size) ..."
    python3 -m tensorrt_llm.llmapi.mgmn_worker_node
fi
