#!/usr/bin/env python3
# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""Unified legacy lint utilities: baseline-gated ruff + config generation.

Subcommands:

  lint-precommit FILE1.py FILE2.py ...
      Runs ruff --fix on the given files, detects auto-fixed modifications via
      file hashing, parses remaining violations from JSON output, and compares
      against the committed baseline. Fails on regressions (new violations
      exceeding the baseline count for a given file+rule pair) or when files
      are auto-modified by ruff --fix (to prompt re-staging).

  lint-update-violations
      Scans ALL legacy files and writes/overwrites ruff-legacy-baseline.json.
      Run this after batch cleanups or periodically to tighten the ratchet.

  gen-configs
      Regenerate ruff-legacy.toml and managed blocks in pyproject.toml /
      .pre-commit-config.yaml from legacy-files.txt (single source of truth).

  check-configs
      Verify generated configs are fresh (CI mode).

  prune-files
      Remove stale entries from legacy-files.txt.

Stdlib-only (no pip dependencies beyond ruff and jinja2).
"""

from __future__ import annotations

import argparse
import difflib
import hashlib
import json
import os
import subprocess
import sys
from collections import defaultdict
from pathlib import Path

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
REPO_ROOT = Path(__file__).resolve().parent.parent
LEGACY_FILES_TXT = REPO_ROOT / "legacy-files.txt"
BASELINE_PATH = REPO_ROOT / "ruff-legacy-baseline.json"
RUFF_CONFIG = REPO_ROOT / "ruff-legacy.toml"
RUFF_LEGACY_TOML = RUFF_CONFIG
PYPROJECT_TOML = REPO_ROOT / "pyproject.toml"
PRECOMMIT_YAML = REPO_ROOT / ".pre-commit-config.yaml"
TEMPLATES_DIR = REPO_ROOT / "scripts" / "templates"

# Maximum files per ruff invocation (avoids OS arg-length limits)
BATCH_SIZE = 500

# Marker strings used to delimit auto-generated blocks
BEGIN_MARKER = "# <<<< BEGIN AUTO-GENERATED by scripts/legacy_utils.py gen-configs >>>>"
END_MARKER = "# <<<< END AUTO-GENERATED >>>>"


# ---------------------------------------------------------------------------
# Exceptions
# ---------------------------------------------------------------------------


class RuffError(RuntimeError):
    """Raised when ruff fails unexpectedly or returns unparsable output."""


# ---------------------------------------------------------------------------
# Shared helpers
# ---------------------------------------------------------------------------


def eprint(*args, **kwargs):
    """Print to stderr (pre-commit convention)."""
    print(*args, file=sys.stderr, **kwargs)


def read_legacy_files() -> list[str]:
    """Read legacy-files.txt, return sorted non-empty non-comment lines.

    Raises FileNotFoundError if legacy-files.txt does not exist.
    """
    if not LEGACY_FILES_TXT.exists():
        raise FileNotFoundError(f"{LEGACY_FILES_TXT} not found")
    paths = []
    for line in LEGACY_FILES_TXT.read_text().splitlines():
        line = line.strip()
        if line and not line.startswith("#"):
            paths.append(line)
    return sorted(set(paths))


def hash_file(path: Path) -> str:
    """Return SHA-256 hex digest of a file's contents."""
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(8192), b""):
            h.update(chunk)
    return h.hexdigest()


def hash_files(paths: list[Path]) -> dict[Path, str]:
    """Return {path: sha256} for all given files."""
    return {p: hash_file(p) for p in paths if p.exists()}


def normalize_path(filepath: str, repo_root: Path) -> str:
    """Normalize an absolute path to repo-relative."""
    p = Path(filepath)
    if p.is_absolute():
        try:
            return str(p.relative_to(repo_root))
        except ValueError:
            return str(p)
    return str(p)


def count_violations(violations: list[dict], repo_root: Path) -> dict[str, dict[str, int]]:
    """Count violations per (file, rule) from ruff JSON output.

    Skips entries with code=null (syntax errors).
    Returns: {file_path: {rule_code: count}}
    """
    counts: dict[str, dict[str, int]] = defaultdict(lambda: defaultdict(int))
    for v in violations:
        code = v.get("code")
        if code is None:
            continue
        filepath = normalize_path(v.get("filename", ""), repo_root)
        counts[filepath][code] += 1
    return counts


def load_baseline() -> dict:
    """Load the baseline JSON file, stripping _meta key.

    Raises FileNotFoundError if the baseline file does not exist.
    """
    if not BASELINE_PATH.exists():
        try:
            display_path = str(BASELINE_PATH.relative_to(REPO_ROOT))
        except ValueError:
            display_path = str(BASELINE_PATH)
        raise FileNotFoundError(
            f"Baseline file not found: {display_path}\n"
            f"Run: python scripts/legacy_utils.py lint-update-violations"
        )
    with open(BASELINE_PATH) as f:
        data = json.load(f)
    data.pop("_meta", None)
    return data


def run_ruff_json(files: list[str], fix: bool = True) -> list[dict]:
    """Run ruff check --output-format json on the given files.

    When *fix* is True (default), ``--fix`` is included so ruff auto-corrects
    fixable violations. When False, violations are only counted.

    Returns the parsed JSON array of remaining violations.
    Raises RuffError on unexpected failures or unparsable output.
    """
    if not files:
        return []

    all_violations = []
    for i in range(0, len(files), BATCH_SIZE):
        batch = files[i : i + BATCH_SIZE]
        cmd = [
            "ruff",
            "check",
            "--config",
            str(RUFF_CONFIG),
        ]
        if fix:
            cmd.append("--fix")
        cmd += [
            "--exit-zero",
            "--output-format",
            "json",
        ] + batch

        result = subprocess.run(cmd, capture_output=True, text=True)
        if result.returncode != 0 and not result.stdout.strip():
            raise RuffError(f"ruff failed unexpectedly:\n{result.stderr}")

        if result.stdout.strip():
            try:
                violations = json.loads(result.stdout)
                all_violations.extend(violations)
            except json.JSONDecodeError:
                raise RuffError(f"Could not parse ruff JSON output:\n{result.stdout[:500]}")

    return all_violations


def compare_against_baseline(
    current_counts: dict[str, dict[str, int]],
    baseline: dict[str, dict[str, int]],
    checked_files: set[str],
) -> tuple[list[tuple[str, str, int]], list[tuple[str, str, int]]]:
    """Compare current violation counts against baseline.

    Returns (regressions, improvements), each a list of (filepath, rule, delta).
    """
    regressions = []
    for filepath, rules in sorted(current_counts.items()):
        file_baseline = baseline.get(filepath, {})
        if isinstance(file_baseline, dict):
            for rule, count in sorted(rules.items()):
                baseline_count = file_baseline.get(rule, 0)
                if count > baseline_count:
                    regressions.append((filepath, rule, count - baseline_count))

    improvements = []
    for filepath in sorted(checked_files):
        file_baseline = baseline.get(filepath, {})
        if not isinstance(file_baseline, dict):
            continue
        file_current = current_counts.get(filepath, {})
        for rule, baseline_count in file_baseline.items():
            current_count = file_current.get(rule, 0)
            if current_count < baseline_count:
                improvements.append((filepath, rule, baseline_count - current_count))

    return regressions, improvements


def identify_new_violations(
    violations: list[dict],
    baseline: dict[str, dict[str, int]],
    repo_root: Path,
) -> list[tuple[str, int, str, str]]:
    """Identify individual violations that exceed the baseline.

    For each (file, rule) pair where current count > baseline count,
    includes ALL violations for that pair (we can't know which specific
    line is "new", so showing all is most actionable).

    Returns list of (filepath, line, code, message) sorted by filepath then line.
    Skips violations with code=None (syntax errors).
    """
    current_counts = count_violations(violations, repo_root)

    regressed_pairs: set[tuple[str, str]] = set()
    for filepath, rules in current_counts.items():
        file_baseline = baseline.get(filepath, {})
        if isinstance(file_baseline, dict):
            for rule, count in rules.items():
                if count > file_baseline.get(rule, 0):
                    regressed_pairs.add((filepath, rule))

    results: list[tuple[str, int, str, str]] = []
    for v in violations:
        code = v.get("code")
        if code is None:
            continue
        filepath = normalize_path(v.get("filename", ""), repo_root)
        if (filepath, code) in regressed_pairs:
            line = v.get("location", {}).get("row", 0)
            message = v.get("message", "")
            results.append((filepath, line, code, message))

    results.sort(key=lambda t: (t[0], t[1]))
    return results


def format_improvements(
    improvements: list[tuple[str, str, int]],
) -> list[str]:
    """Format improvement tuples as display lines.

    Returns list of "  filepath  rule (-delta)" strings, sorted by filepath then rule.
    """
    return [f"  {filepath}  {rule} (-{delta})" for filepath, rule, delta in sorted(improvements)]


# ---------------------------------------------------------------------------
# Config generation helpers
# ---------------------------------------------------------------------------


def validate_paths(paths: list[str]) -> list[str]:
    """Warn about paths that don't exist on disk. Return list of stale paths."""
    stale = []
    for p in paths:
        if not (REPO_ROOT / p).exists():
            stale.append(p)
    if stale:
        eprint(f"WARNING: {len(stale)} stale entries in legacy-files.txt:")
        for s in stale:
            eprint(f"  {s}")
    return stale


def render_template(template_name: str, paths: list[str]) -> str:
    """Render a Jinja2 template with the given paths list."""
    from jinja2 import Environment, FileSystemLoader

    env = Environment(
        loader=FileSystemLoader(str(TEMPLATES_DIR)),
        keep_trailing_newline=True,
    )
    template = env.get_template(template_name)
    return template.render(paths=paths)


def replace_managed_block(content: str, new_block: str) -> str:
    """Replace content between BEGIN/END markers with new_block.

    The new_block should include the BEGIN and END markers themselves.
    """
    begin_idx = content.find(BEGIN_MARKER)
    end_idx = content.find(END_MARKER, begin_idx + len(BEGIN_MARKER)) if begin_idx != -1 else -1

    if begin_idx == -1 or end_idx == -1:
        raise ValueError(
            f"Could not find managed block markers:\n  BEGIN: {BEGIN_MARKER}\n  END:   {END_MARKER}"
        )

    nl = content.find("\n", end_idx)
    end_line_end = (nl + 1) if nl != -1 else len(content)

    return content[:begin_idx] + new_block + content[end_line_end:]


def show_diff(label: str, old: str, new: str) -> bool:
    """Print unified diff if different. Return True if they differ."""
    if old == new:
        return False
    diff = difflib.unified_diff(
        old.splitlines(keepends=True),
        new.splitlines(keepends=True),
        fromfile=f"a/{label}",
        tofile=f"b/{label}",
    )
    sys.stdout.writelines(diff)
    return True


def generate_ruff_legacy_toml(paths: list[str]) -> str:
    """Generate the full ruff-legacy.toml content."""
    return render_template("ruff-legacy.toml.j2", paths)


def generate_pyproject_block(paths: list[str]) -> str:
    """Generate the managed block for pyproject.toml [tool.ruff.format] exclude."""
    return render_template("pyproject-format-exclude.j2", paths)


def generate_precommit_block(paths: list[str]) -> str:
    """Generate the managed block for .pre-commit-config.yaml file anchors."""
    return render_template("precommit-legacy-files.j2", paths)


# ---------------------------------------------------------------------------
# Config generation actions
# ---------------------------------------------------------------------------


def do_generate(paths: list[str]) -> None:
    """Write all generated files in-place.

    Computes all outputs first so that if any marker is missing,
    no files are written (atomic with respect to validation).
    """
    new_toml = generate_ruff_legacy_toml(paths)

    old_pyproject = PYPROJECT_TOML.read_text()
    new_pyproject_block = generate_pyproject_block(paths)
    new_pyproject = replace_managed_block(old_pyproject, new_pyproject_block)

    old_precommit = PRECOMMIT_YAML.read_text()
    new_precommit_block = generate_precommit_block(paths)
    new_precommit = replace_managed_block(old_precommit, new_precommit_block)

    RUFF_LEGACY_TOML.write_text(new_toml)
    print(f"  Written: {RUFF_LEGACY_TOML.relative_to(REPO_ROOT)}")

    PYPROJECT_TOML.write_text(new_pyproject)
    print(f"  Updated: {PYPROJECT_TOML.relative_to(REPO_ROOT)}")

    PRECOMMIT_YAML.write_text(new_precommit)
    print(f"  Updated: {PRECOMMIT_YAML.relative_to(REPO_ROOT)}")


def do_check(paths: list[str]) -> None:
    """Check freshness -- exit 1 with diff if any file is stale."""
    any_stale = False

    expected = generate_ruff_legacy_toml(paths)
    actual = RUFF_LEGACY_TOML.read_text() if RUFF_LEGACY_TOML.exists() else ""
    if show_diff("ruff-legacy.toml", actual, expected):
        any_stale = True

    old_pyproject = PYPROJECT_TOML.read_text()
    new_block = generate_pyproject_block(paths)
    expected_pyproject = replace_managed_block(old_pyproject, new_block)
    if show_diff("pyproject.toml", old_pyproject, expected_pyproject):
        any_stale = True

    old_precommit = PRECOMMIT_YAML.read_text()
    new_block = generate_precommit_block(paths)
    expected_precommit = replace_managed_block(old_precommit, new_block)
    if show_diff(".pre-commit-config.yaml", old_precommit, expected_precommit):
        any_stale = True

    if any_stale:
        eprint(
            "\nERROR: Generated configs are out of date. Run:\n"
            "  python scripts/legacy_utils.py gen-configs\n"
        )
        sys.exit(1)
    else:
        print("All generated configs are up to date.")


def do_prune() -> None:
    """Remove stale paths from legacy-files.txt."""
    paths = read_legacy_files()
    stale = validate_paths(paths)
    if not stale:
        print("No stale entries found.")
        return
    valid = [p for p in paths if p not in set(stale)]
    LEGACY_FILES_TXT.write_text("\n".join(valid) + "\n")
    print(f"Pruned {len(stale)} stale entries. {len(valid)} entries remain.")


# ---------------------------------------------------------------------------
# Pre-commit mode
# ---------------------------------------------------------------------------


def precommit_mode(file_args: list[str]) -> int:
    """Run the pre-commit check. Returns exit code."""
    repo_root = REPO_ROOT
    baseline = load_baseline()

    abs_paths = []
    for f in file_args:
        p = Path(f)
        if not p.is_absolute():
            p = Path.cwd() / p
        p = p.resolve()
        abs_paths.append(p)

    hashes_before = hash_files(abs_paths)

    str_paths = [str(p) for p in abs_paths]
    violations = run_ruff_json(str_paths)

    hashes_after = hash_files(abs_paths)

    modified_files = []
    for p in abs_paths:
        before = hashes_before.get(p)
        after = hashes_after.get(p)
        if before and after and before != after:
            modified_files.append(normalize_path(str(p), repo_root))

    current_counts = count_violations(violations, repo_root)

    checked_files = {normalize_path(str(p), repo_root) for p in abs_paths}
    regressions, improvements = compare_against_baseline(current_counts, baseline, checked_files)

    has_failure = bool(modified_files) or bool(regressions)

    if modified_files:
        eprint(f"\nAuto-fixed {len(modified_files)} file(s):")
        for f in sorted(modified_files):
            eprint(f"  {f}")

    if regressions:
        new_violations = identify_new_violations(violations, baseline, repo_root)
        eprint(f"\nNew violations ({len(new_violations)} regressions vs baseline):\n")
        for filepath, line, code, message in new_violations:
            eprint(f"  {filepath}:{line}  {code}  {message}")
        eprint("\nTo inspect: ruff check --config ruff-legacy.toml <file>")

    if has_failure:
        eprint("\nRe-stage modified files and fix new violations, then commit again.")
        return 1

    if improvements:
        total = sum(delta for _, _, delta in improvements)
        n_files = len({f for f, _, _ in improvements})
        eprint(f"\nTip: {total} violation(s) resolved in {n_files} file(s). Run:")
        eprint("  python scripts/legacy_utils.py lint-update-violations")
        eprint("to tighten the baseline.\n")
        for line in format_improvements(improvements):
            eprint(line)

    return 0


# ---------------------------------------------------------------------------
# Update baseline mode
# ---------------------------------------------------------------------------


def update_baseline_mode() -> int:
    """Scan all legacy files and write the baseline JSON. Returns exit code."""
    repo_root = REPO_ROOT

    legacy_paths = read_legacy_files()
    existing = [p for p in legacy_paths if (repo_root / p).exists()]
    eprint(
        f"Scanning {len(existing)} legacy files ({len(legacy_paths) - len(existing)} missing)..."
    )

    violations = run_ruff_json(existing, fix=False)
    counts = count_violations(violations, repo_root)

    total_violations = 0
    total_files = 0
    baseline = {}
    for filepath in sorted(counts.keys()):
        rules = counts[filepath]
        baseline[filepath] = dict(sorted(rules.items()))
        total_violations += sum(rules.values())
        total_files += 1

    output = {
        "_meta": {
            "generated_by": "scripts/legacy_utils.py lint-update-violations",
            "total_violations": total_violations,
            "total_files": total_files,
        },
    }
    output.update(baseline)

    with open(BASELINE_PATH, "w") as f:
        json.dump(output, f, indent=2)
        f.write("\n")

    eprint(f"Baseline written: {BASELINE_PATH.relative_to(repo_root)}")
    eprint(f"  {total_violations} violations across {total_files} files")
    return 0


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def _build_parser() -> argparse.ArgumentParser:
    """Build the CLI argument parser with subcommands."""
    parser = argparse.ArgumentParser(
        description="Unified legacy lint utilities: baseline-gated ruff + config generation."
    )
    subparsers = parser.add_subparsers(dest="command")

    # lint-precommit
    sp_precommit = subparsers.add_parser(
        "lint-precommit",
        help="Run baseline-gated ruff lint on given files (pre-commit hook)",
    )
    sp_precommit.add_argument("files", nargs="+", help="Files to check")

    # lint-update-violations
    subparsers.add_parser(
        "lint-update-violations",
        help="Scan ALL legacy files and write/overwrite ruff-legacy-baseline.json",
    )

    # gen-configs
    subparsers.add_parser(
        "gen-configs",
        help="Regenerate ruff-legacy.toml and managed blocks from legacy-files.txt",
    )

    # check-configs
    subparsers.add_parser(
        "check-configs",
        help="Verify generated configs are up to date (CI mode)",
    )

    # prune-files
    subparsers.add_parser(
        "prune-files",
        help="Remove stale paths from legacy-files.txt",
    )

    return parser


def main() -> int:
    parser = _build_parser()
    args = parser.parse_args()

    try:
        if args.command == "lint-precommit":
            return precommit_mode(args.files)

        if args.command == "lint-update-violations":
            return update_baseline_mode()

        if args.command in ("gen-configs", "check-configs", "prune-files"):
            os.chdir(REPO_ROOT)

        if args.command == "prune-files":
            do_prune()
            return 0

        if args.command in ("gen-configs", "check-configs"):
            paths = read_legacy_files()
            stale = validate_paths(paths)

            if stale and args.command == "gen-configs":
                eprint(
                    "HINT: Run 'python scripts/legacy_utils.py prune-files' to remove stale entries."
                )

            if args.command == "check-configs":
                do_check(paths)
            else:
                do_generate(paths)
            return 0

        # No subcommand
        parser.print_help(sys.stderr)
        return 1

    except FileNotFoundError as e:
        eprint(f"ERROR: {e}")
        return 1
    except RuffError as e:
        eprint(f"ERROR: {e}")
        return 1


if __name__ == "__main__":
    sys.exit(main())
