# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""Regenerate the public model architecture allowlist used by telemetry.

The inputs are checked-in, public TensorRT-LLM model catalogs. This script is
intentionally offline: updating the runtime allowlist must not depend on a
network request or on importing model implementations.
"""

from __future__ import annotations

import argparse
import ast
import re
import sys
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parents[1]
_ARCH_INDEX_PATH = _REPO_ROOT / "tensorrt_llm" / "_torch" / "models" / "_arch_index.py"
_SUPPORTED_MODELS_PATH = _REPO_ROOT / "docs" / "source" / "models" / "supported-models.md"
_OUTPUT_PATH = _REPO_ROOT / "tensorrt_llm" / "usage" / "architecture_allowlist.py"
_ARCHITECTURE_CELL_PATTERN = re.compile(r"`([A-Za-z_][A-Za-z0-9_]*)`")


def _architecture_index_names(path: Path) -> set[str]:
    """Read public architecture keys without importing the model package."""
    module = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
    for node in module.body:
        if not isinstance(node, (ast.Assign, ast.AnnAssign)):
            continue
        targets = node.targets if isinstance(node, ast.Assign) else [node.target]
        if not any(
            isinstance(target, ast.Name) and target.id == "MODEL_ARCH_TO_MODULE"
            for target in targets
        ):
            continue
        value = ast.literal_eval(node.value)
        if not isinstance(value, dict) or not all(isinstance(name, str) for name in value):
            raise ValueError(f"MODEL_ARCH_TO_MODULE in {path} must be a string-keyed literal dict")
        return set(value)
    raise ValueError(f"MODEL_ARCH_TO_MODULE not found in {path}")


def _supported_model_names(path: Path) -> set[str]:
    """Extract architecture cells from the public supported-model tables."""
    architectures: set[str] = set()
    architecture_table = False
    for line in path.read_text(encoding="utf-8").splitlines():
        if not line.startswith("|"):
            architecture_table = False
            continue
        cells = [cell.strip() for cell in line.strip().strip("|").split("|")]
        if not cells:
            continue
        if "Architecture" in cells[0] or "architecture" in cells[0]:
            architecture_table = True
            continue
        if architecture_table:
            architectures.update(_ARCHITECTURE_CELL_PATTERN.findall(cells[0]))
    if not architectures:
        raise ValueError(f"No architecture table entries found in {path}")
    return architectures


def _render(architectures: set[str]) -> str:
    """Render the deterministic checked-in runtime module."""
    sorted_names = sorted(architectures)
    entries = "\n".join(f'        "{name}",' for name in sorted_names)
    return f'''# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""Public architecture names that telemetry may report in plaintext.

Generated by ``scripts/update_telemetry_architecture_allowlist.py`` from the
checked-in public TensorRT-LLM model catalogs. Do not edit by hand.
"""

PUBLIC_HF_ARCHITECTURES = frozenset(
    {{
{entries}
    }}
)
'''


def _expected_content() -> str:
    architectures = _architecture_index_names(_ARCH_INDEX_PATH)
    architectures.update(_supported_model_names(_SUPPORTED_MODELS_PATH))
    return _render(architectures)


def _parse_args(argv: list[str] | None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if the checked-in allowlist is not synchronized with its public sources",
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    """Regenerate the allowlist or verify that it is synchronized.

    Args:
        argv: Optional command-line arguments. Pass ``--check`` to compare the
            checked-in module with the public model catalogs without writing it.

    Returns:
        Zero on success, or one when ``--check`` finds stale generated output.
    """
    args = _parse_args(argv)
    expected = _expected_content()
    if args.check:
        if not _OUTPUT_PATH.exists() or _OUTPUT_PATH.read_text(encoding="utf-8") != expected:
            print(
                f"{_OUTPUT_PATH.relative_to(_REPO_ROOT)} is stale; run "
                f"{Path(__file__).relative_to(_REPO_ROOT)}",
                file=sys.stderr,
            )
            return 1
        return 0

    _OUTPUT_PATH.write_text(expected, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
