max_batch_size: 8
max_seq_len: 66048

tensor_parallel_size: 2
pipeline_parallel_size: 2
moe_expert_parallel_size: 2
context_parallel_size: 1

nvfp4_gemm_config:
  allowed_backends: [marlin]
moe_config:
  backend: MARLIN
