FROM nvidia/cuda:12.3.0-devel-ubuntu22.04

RUN apt-get update && apt-get -y install python3.10 python3-pip openmpi-bin libopenmpi-dev git git-lfs

RUN pip3 install tensorrt_llm==0.9.0 --extra-index-url https://pypi.nvidia.com

RUN pip3 install numpy==1.26.4

RUN git clone https://github.com/NVIDIA/TensorRT-LLM.git && cd TensorRT-LLM && git checkout v0.9.0