# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Authorized real-checkpoint quality gate for MiniMax-H3.

The public checkpoint license excludes this CI territory. The test therefore
requires an explicit authorization flag and externally provisioned approved
checkpoint/golden paths. It never downloads MiniMax-H3 itself.

The checkpoint's ``assets/t2va.mp4`` was generated through the released SGLang
server and is useful as a serving example, but it is not a Diffusers parity
oracle. The quality gate instead consumes tensors generated by the pinned
Diffusers implementation from the same approved checkpoint.

"""

import hashlib
import json
import os
from pathlib import Path

import pytest
import torch
import torch.nn.functional as F
from defs.examples.visual_gen.visual_gen_test_utils import (
    _cleanup_cuda,
    _disable_inductor_compile_worker_quiesce,
)
from PIL import Image

MINIMAX_H3_PROMPT = "\n".join(
    (
        " ".join(
            (
                "integrated_multimodal_description: [Shot 1] Cinematic, medium wide shot, pushing in",
                "slowly. In the cavernous, dimly lit bridge of a starship, sleek metallic consoles with",
                "glowing amber displays flank a massive, curved observation window. A female captain, in",
                "her late 40s with an athletic build and short silver-streaked black hair, stands in the",
                "center midground. She wears a structured, high-collared dark navy military tunic with",
                "silver chest insignias. Her back is to the camera, silhouetted against the cool, ambient",
                "starlight pouring through the thick glass. She stands perfectly still with her hands",
                "clasped tightly behind her back. Outside the window, a massive armada of jagged, dark",
                "grey dreadnoughts hovers in tight formation against a deep purple space nebula. The",
                "fleet's massive rear thrusters begin to glow with an intense, escalating bright blue",
                "light. [Shot 2] At 00:04.500, the camera cuts to a close-up of the captain's face and",
                "shakes strongly. The brilliant blue-white light from the fleet's gathering energy",
                "reflects vividly in her dark eyes. Suddenly, a blinding white flash floods through the",
                "window, completely washing out the background as the fleet jumps to hyperspace. The",
                "sheer spatial force violently jolts the bridge, causing the captain from Shot 1 to",
                "stagger slightly forward, her shoulders tensing as she visibly braces herself against",
                "the physical tremors. As the intense white light fades abruptly, leaving only the dim,",
                "empty expanse of the purple nebula reflected on her starkly lit skin, her jaw clenches,",
                "and she slowly closes her eyes in the newly emptied space.",
            )
        ),
        " ".join(
            (
                "overall_soundscape: A low, resonant hum of the ship's ambient life support systems",
                "serves as the baseline, soon drowned out by an audible, escalating, high-pitched",
                "electronic whine as the fleet outside charges its hyperdrives. A massive, deafening,",
                "bass-heavy boom and sharp crackle erupts during the blinding flash, accompanied by the",
                "loud metallic creaking, rattling, and deep thuds of the bridge's bulkheads vibrating",
                "under immense physical stress. The intense roaring impact then cuts abruptly back to a",
                "hollow, echoing room tone, leaving only the faint, steady hum of the isolated bridge.",
            )
        ),
        " ".join(
            (
                "non_diegetic_music: Cinematic space-opera orchestral score, slow tempo, featuring a",
                "solitary, mournful French horn melody over deep, sustained string dissonances that build",
                "rapidly in volume and intensity, swelling to a massive orchestral peak before snapping",
                "immediately into silence right after the jump.",
            )
        ),
    )
)
MINIMAX_H3_QUALITY_HEIGHT = 128
MINIMAX_H3_QUALITY_WIDTH = 128
MINIMAX_H3_SMOKE_NUM_FRAMES = 124
MINIMAX_H3_QUALITY_NUM_FRAMES = 124
MINIMAX_H3_NUM_INFERENCE_STEPS = 50
MINIMAX_H3_SEED = 0
# Calibrated against the exact golden digest below. The validated implementation
# measured 0.01737 LPIPS and 0.006861 audio log-STFT distance; 0.05 leaves room
# for supported GPU-kernel drift without weakening the regression signal.
MINIMAX_H3_LPIPS_THRESHOLD = 0.05
MINIMAX_H3_AUDIO_LOG_STFT_THRESHOLD = 0.05
MINIMAX_H3_LPIPS_BATCH_SIZE = 16
MINIMAX_H3_MODEL_ID = "MiniMaxAI/MiniMax-H3"
MINIMAX_H3_CHECKPOINT_REVISION = "5d9b308a59ab12e67147f191e184baf704185bd1"
MINIMAX_H3_DIFFUSERS_REPOSITORY = "https://github.com/huggingface/diffusers"
MINIMAX_H3_DIFFUSERS_PULL_REQUEST = 14355
MINIMAX_H3_DIFFUSERS_REVISION = "abc5e9bf71fd38f53cd471bc3acaa84bc5ecbfdc"
MINIMAX_H3_T2VA_CHECKPOINT_MANIFEST_SHA256 = (
    "750629c440a7b18074d729a616d28fbdb54800589c68e56fa87c0ffa3245ce29"
)
MINIMAX_H3_GOLDEN_RUNTIME_PROVENANCE = {
    "accelerate": "1.14.0",
    "compute_capability": [10, 3],
    "cuda": "13.2",
    "cuda_matmul_allow_tf32": True,
    "cudnn": 92200,
    "cudnn_allow_tf32": True,
    "diffusers": "0.40.0.dev0",
    "driver": "610.47.04",
    "float32_matmul_precision": "high",
    "gpu": "NVIDIA GB300",
    "huggingface_hub": "1.14.0",
    "numpy": "2.3.5",
    "pillow": "12.3.0",
    "python": "3.12.3",
    "python_implementation": "CPython",
    "safetensors": "0.8.0",
    "tokenizers": "0.22.2",
    "torch": "2.12.0a0+5aff3928d8.nv26.05",
    "transformers": "5.5.4",
}
MINIMAX_H3_GOLDEN_CONTENT_SHA256 = (
    "1c548afc70d40325520c00ae56aae86e39d18c1129459229f547372c63a3ad70"
)


def _required_authorized_path(env_var: str, label: str, *, is_dir: bool) -> str:
    path = os.environ.get(env_var, "")
    if not path:
        pytest.fail(f"{env_var} must identify the provisioned {label}.")
    exists = os.path.isdir(path) if is_dir else os.path.isfile(path)
    if not exists:
        pytest.fail(f"Provisioned {label} not found: {path}")
    return path


def _authorized_checkpoint_path() -> str:
    return _required_authorized_path(
        "MINIMAX_H3_CHECKPOINT",
        "authorized MiniMax-H3 checkpoint",
        is_dir=True,
    )


def _diffusers_golden_metadata() -> dict[str, object]:
    return {
        "schema_version": 2,
        "source": "diffusers.ModularPipeline",
        "model_id": MINIMAX_H3_MODEL_ID,
        "checkpoint_revision": MINIMAX_H3_CHECKPOINT_REVISION,
        "t2va_checkpoint_manifest_sha256": MINIMAX_H3_T2VA_CHECKPOINT_MANIFEST_SHA256,
        "diffusers_repository": MINIMAX_H3_DIFFUSERS_REPOSITORY,
        "diffusers_pull_request": MINIMAX_H3_DIFFUSERS_PULL_REQUEST,
        "diffusers_revision": MINIMAX_H3_DIFFUSERS_REVISION,
        "runtime_provenance": MINIMAX_H3_GOLDEN_RUNTIME_PROVENANCE,
        "prompt_sha256": hashlib.sha256(MINIMAX_H3_PROMPT.encode()).hexdigest(),
        "seed": MINIMAX_H3_SEED,
        "height": MINIMAX_H3_QUALITY_HEIGHT,
        "width": MINIMAX_H3_QUALITY_WIDTH,
        "num_frames": MINIMAX_H3_QUALITY_NUM_FRAMES,
        "num_inference_steps": MINIMAX_H3_NUM_INFERENCE_STEPS,
        "frame_rate": 24.0,
        "audio_sample_rate": 32000,
        "dtype": "bfloat16",
        "output_type": "pt",
    }


def _golden_content_sha256(
    metadata: dict[str, object],
    video: torch.Tensor,
    audio: torch.Tensor,
) -> str:
    digest = hashlib.sha256()
    digest.update(json.dumps(metadata, sort_keys=True, separators=(",", ":")).encode())
    for name, tensor in (("video", video), ("audio", audio)):
        tensor = tensor.detach().cpu().contiguous()
        digest.update(name.encode())
        digest.update(str(tensor.dtype).encode())
        digest.update(json.dumps(list(tensor.shape), separators=(",", ":")).encode())
        digest.update(tensor.numpy().tobytes())
    return digest.hexdigest()


def _multi_resolution_log_stft_distance(
    actual: torch.Tensor,
    expected: torch.Tensor,
) -> float:
    if actual.shape != expected.shape:
        raise AssertionError(
            f"Audio shape mismatch: generated {tuple(actual.shape)}, "
            f"golden {tuple(expected.shape)}."
        )
    actual = actual.float().reshape(-1, actual.shape[-1])
    expected = expected.float().reshape(-1, expected.shape[-1])
    distances: list[torch.Tensor] = []
    for n_fft in (512, 1024, 2048):
        hop_length = n_fft // 4
        window = torch.hann_window(n_fft)
        actual_stft = torch.stft(
            actual,
            n_fft=n_fft,
            hop_length=hop_length,
            window=window,
            return_complex=True,
        ).abs()
        expected_stft = torch.stft(
            expected,
            n_fft=n_fft,
            hop_length=hop_length,
            window=window,
            return_complex=True,
        ).abs()
        distances.append(F.l1_loss(torch.log1p(actual_stft), torch.log1p(expected_stft)))
    return float(torch.stack(distances).mean())


def _load_diffusers_golden(golden_path: str) -> tuple[torch.Tensor, torch.Tensor]:
    golden = torch.load(golden_path, map_location="cpu", weights_only=True)
    if not isinstance(golden, dict) or not {"metadata", "video", "audio"}.issubset(golden):
        raise AssertionError(
            "The MiniMax-H3 Diffusers golden must be a tensor dictionary with "
            "'metadata', 'video', and 'audio' entries."
        )

    metadata = golden["metadata"]
    expected_metadata = _diffusers_golden_metadata()
    if metadata != expected_metadata:
        raise AssertionError(
            "MiniMax-H3 Diffusers golden provenance mismatch:\n"
            f"expected {expected_metadata}\n"
            f"got {metadata}"
        )
    video = golden["video"].detach().float()
    audio = golden["audio"].detach().float()
    expected_video_shape = (
        1,
        MINIMAX_H3_QUALITY_NUM_FRAMES,
        3,
        MINIMAX_H3_QUALITY_HEIGHT,
        MINIMAX_H3_QUALITY_WIDTH,
    )
    if tuple(video.shape) != expected_video_shape:
        raise AssertionError(
            f"Golden video shape must be {expected_video_shape}, got {tuple(video.shape)}."
        )
    if audio.ndim != 3 or audio.shape[:2] != (1, 2):
        raise AssertionError(
            "The MiniMax-H3 Diffusers golden audio must be batched stereo audio, "
            f"got {tuple(audio.shape)}."
        )
    if not torch.isfinite(video).all() or not torch.isfinite(audio).all():
        raise AssertionError("The MiniMax-H3 Diffusers golden contains non-finite values.")
    if video.min() < 0 or video.max() > 1:
        raise AssertionError("The MiniMax-H3 Diffusers golden video must be in [0, 1].")
    content_sha256 = _golden_content_sha256(metadata, video, audio)
    if content_sha256 != MINIMAX_H3_GOLDEN_CONTENT_SHA256:
        raise AssertionError(
            "MiniMax-H3 Diffusers golden content digest mismatch: "
            f"expected {MINIMAX_H3_GOLDEN_CONTENT_SHA256}, got {content_sha256}."
        )
    return video, audio


def _mean_lpips_distance(
    actual: torch.Tensor,
    expected: torch.Tensor,
) -> float:
    import lpips as lpips_package

    if actual.dtype != torch.uint8:
        raise AssertionError(f"Generated video must be uint8, got {actual.dtype}.")
    actual = actual.permute(0, 1, 4, 2, 3).float().div(255.0)
    if actual.shape != expected.shape:
        raise AssertionError(
            f"Video shape mismatch: generated {tuple(actual.shape)}, "
            f"golden {tuple(expected.shape)}."
        )

    actual = actual.flatten(0, 1)
    expected = expected.flatten(0, 1)
    metric = lpips_package.LPIPS(net="alex", verbose=False).cuda().eval()
    scores: list[torch.Tensor] = []
    try:
        with torch.inference_mode():
            for start in range(0, actual.shape[0], MINIMAX_H3_LPIPS_BATCH_SIZE):
                end = start + MINIMAX_H3_LPIPS_BATCH_SIZE
                scores.append(
                    metric(
                        expected[start:end].cuda().mul(2).sub(1),
                        actual[start:end].cuda().mul(2).sub(1),
                    ).cpu()
                )
        return float(torch.cat(scores).mean())
    finally:
        del metric
        _cleanup_cuda()


def test_minimax_h3_authorized_artifact_paths_fail_closed(
    monkeypatch: pytest.MonkeyPatch,
    tmp_path: Path,
) -> None:
    env_var = "MINIMAX_H3_TEST_ARTIFACT"
    monkeypatch.delenv(env_var, raising=False)
    with pytest.raises(pytest.fail.Exception, match=f"{env_var} must identify"):
        _required_authorized_path(env_var, "test artifact", is_dir=False)

    missing_path = tmp_path / "missing.pt"
    monkeypatch.setenv(env_var, str(missing_path))
    with pytest.raises(pytest.fail.Exception, match="test artifact not found"):
        _required_authorized_path(env_var, "test artifact", is_dir=False)

    provisioned_path = tmp_path / "golden.pt"
    provisioned_path.touch()
    monkeypatch.setenv(env_var, str(provisioned_path))
    assert _required_authorized_path(env_var, "test artifact", is_dir=False) == str(
        provisioned_path
    )


def test_minimax_h3_diffusers_golden_digest_is_pinned() -> None:
    assert len(MINIMAX_H3_GOLDEN_CONTENT_SHA256) == 64
    int(MINIMAX_H3_GOLDEN_CONTENT_SHA256, 16)


def test_minimax_h3_diffusers_golden_runtime_provenance_is_complete() -> None:
    assert set(MINIMAX_H3_GOLDEN_RUNTIME_PROVENANCE) == {
        "accelerate",
        "compute_capability",
        "cuda",
        "cuda_matmul_allow_tf32",
        "cudnn",
        "cudnn_allow_tf32",
        "diffusers",
        "driver",
        "float32_matmul_precision",
        "gpu",
        "huggingface_hub",
        "numpy",
        "pillow",
        "python",
        "python_implementation",
        "safetensors",
        "tokenizers",
        "torch",
        "transformers",
    }


@pytest.mark.skipif(
    os.environ.get("MINIMAX_H3_E2E_AUTHORIZED") != "1",
    reason="MiniMax-H3 checkpoint use in this CI territory requires written authorization",
)
@pytest.mark.skipif(not torch.cuda.is_available(), reason="CUDA not available")
def test_minimax_h3_released_transformer_loads_and_runs() -> None:
    """Load every released transformer tensor and compile all model layers."""
    from tensorrt_llm._torch.visual_gen.pipeline_loader import PipelineLoader
    from tensorrt_llm._torch.visual_gen.pipeline_registry import PipelineComponent
    from tensorrt_llm.visual_gen.args import TorchCompileConfig, VisualGenArgs

    checkpoint_path = _authorized_checkpoint_path()
    _disable_inductor_compile_worker_quiesce()
    pipeline = PipelineLoader(
        VisualGenArgs(
            model=checkpoint_path,
            torch_compile_config=TorchCompileConfig(enable=True),
        )
    ).load(
        skip_warmup=True,
        skip_components=[
            PipelineComponent.TOKENIZER,
            PipelineComponent.PROCESSOR,
            PipelineComponent.TEXT_ENCODER,
            PipelineComponent.VAE,
            PipelineComponent.AUDIO_VAE,
            PipelineComponent.SCHEDULER,
            PipelineComponent.AUDIO_SCHEDULER,
        ],
    )
    transformer = None
    output = None
    try:
        transformer = pipeline.transformer
        assert all(
            isinstance(block, torch._dynamo.OptimizedModule)
            for block in transformer.transformer_blocks
        )
        position_ids = torch.tensor(
            [[0, 0, 0], [1, 0, 0], [2, 0, 0], [2, 0, 1], [3, 0, 0]],
            device="cuda",
        )
        torch._dynamo.utils.counters.clear()
        with torch.inference_mode():
            output = transformer(
                hidden_states=torch.randn(1, 2, 96, device="cuda"),
                audio_hidden_states=torch.randn(1, 1, 32, device="cuda"),
                encoder_hidden_states=torch.randn(
                    1,
                    2,
                    5120,
                    device="cuda",
                    dtype=torch.bfloat16,
                ),
                timestep=torch.tensor([1.0], device="cuda"),
                timestep_indices=torch.zeros(5, dtype=torch.long, device="cuda"),
                token_tags=torch.tensor([1, 1, 0, 0, 2], device="cuda"),
                position_ids=position_ids,
                video_indices=torch.tensor([2, 3], device="cuda"),
                audio_indices=torch.tensor([4], device="cuda"),
                text_indices=torch.tensor([0, 1], device="cuda"),
            )

        assert output.sample.shape == (1, 2, 96)
        assert output.audio_sample.shape == (1, 1, 32)
        assert torch.isfinite(output.sample).all()
        assert torch.isfinite(output.audio_sample).all()
        assert torch._dynamo.utils.counters["frames"]["ok"] > 0
        assert not any(parameter.is_meta for parameter in transformer.parameters())
    finally:
        del output
        del transformer
        del pipeline
        _cleanup_cuda()


@pytest.mark.skipif(
    os.environ.get("MINIMAX_H3_E2E_AUTHORIZED") != "1",
    reason="MiniMax-H3 checkpoint use in this CI territory requires written authorization",
)
@pytest.mark.skipif(not torch.cuda.is_available(), reason="CUDA not available")
def test_minimax_h3_released_transformer_dynamic_fp8_compile_smoke() -> None:
    """Dynamically quantize the released BF16 weights and run compiled H3."""
    from tensorrt_llm._torch.visual_gen.pipeline_loader import PipelineLoader
    from tensorrt_llm._torch.visual_gen.pipeline_registry import PipelineComponent
    from tensorrt_llm.quantization.mode import QuantAlgo
    from tensorrt_llm.visual_gen.args import TorchCompileConfig, VisualGenArgs

    checkpoint_path = _authorized_checkpoint_path()
    _disable_inductor_compile_worker_quiesce()
    pipeline = PipelineLoader(
        VisualGenArgs(
            model=checkpoint_path,
            quant_config={"quant_algo": "FP8", "dynamic": True},
            torch_compile_config=TorchCompileConfig(enable=True),
        )
    ).load(
        skip_warmup=True,
        skip_components=[
            PipelineComponent.TOKENIZER,
            PipelineComponent.PROCESSOR,
            PipelineComponent.TEXT_ENCODER,
            PipelineComponent.VAE,
            PipelineComponent.AUDIO_VAE,
            PipelineComponent.SCHEDULER,
            PipelineComponent.AUDIO_SCHEDULER,
        ],
    )
    transformer = None
    output = None
    try:
        transformer = pipeline.transformer
        assert transformer.model_config.quant_config.quant_algo == QuantAlgo.FP8
        assert transformer.model_config.dynamic_weight_quant
        assert all(
            isinstance(block, torch._dynamo.OptimizedModule)
            for block in transformer.transformer_blocks
        )
        assert all(
            module.weight.dtype == torch.float8_e4m3fn
            for module in (
                transformer.context_embedder,
                transformer.proj_in,
                transformer.audio_proj_in,
                transformer.proj_out,
                transformer.audio_proj_out,
            )
        )

        position_ids = torch.tensor(
            [[0, 0, 0], [1, 0, 0], [2, 0, 0], [2, 0, 1], [3, 0, 0]],
            device="cuda",
        )
        torch._dynamo.utils.counters.clear()
        with torch.inference_mode():
            output = transformer(
                hidden_states=torch.randn(1, 2, 96, device="cuda"),
                audio_hidden_states=torch.randn(1, 1, 32, device="cuda"),
                encoder_hidden_states=torch.randn(
                    1,
                    2,
                    5120,
                    device="cuda",
                    dtype=torch.bfloat16,
                ),
                timestep=torch.tensor([1.0], device="cuda"),
                timestep_indices=torch.zeros(5, dtype=torch.long, device="cuda"),
                token_tags=torch.tensor([1, 1, 0, 0, 2], device="cuda"),
                position_ids=position_ids,
                video_indices=torch.tensor([2, 3], device="cuda"),
                audio_indices=torch.tensor([4], device="cuda"),
                text_indices=torch.tensor([0, 1], device="cuda"),
            )

        assert output.sample.shape == (1, 2, 96)
        assert output.audio_sample.shape == (1, 1, 32)
        assert torch.isfinite(output.sample).all()
        assert torch.isfinite(output.audio_sample).all()
        assert torch._dynamo.utils.counters["frames"]["ok"] > 0
    finally:
        del output
        del transformer
        del pipeline
        torch._dynamo.reset()
        _cleanup_cuda()


@pytest.mark.skipif(
    os.environ.get("MINIMAX_H3_E2E_AUTHORIZED") != "1",
    reason="MiniMax-H3 checkpoint use in this CI territory requires written authorization",
)
@pytest.mark.skipif(not torch.cuda.is_available(), reason="CUDA not available")
def test_minimax_h3_released_pipeline_smoke() -> None:
    """Load all components and execute both T2VA and first/last-frame FL2VA."""
    from tensorrt_llm._torch.visual_gen.pipeline_loader import PipelineLoader
    from tensorrt_llm.visual_gen.args import TorchCompileConfig, VisualGenArgs

    checkpoint_path = _authorized_checkpoint_path()
    _disable_inductor_compile_worker_quiesce()
    pipeline = PipelineLoader(
        VisualGenArgs(
            model=checkpoint_path,
            torch_compile_config=TorchCompileConfig(enable=True),
        )
    ).load(skip_warmup=True)
    output = None
    conditioned_output = None
    try:
        output = pipeline.forward(
            prompt="A red fox walking through snow",
            seed=MINIMAX_H3_SEED,
            height=128,
            width=128,
            num_frames=MINIMAX_H3_SMOKE_NUM_FRAMES,
            frame_rate=24.0,
            # MiniMax-H3 counts both endpoints in its sigma grid, so two
            # grid points execute one denoising evaluation.
            num_inference_steps=2,
        )

        assert output.video.shape == (1, MINIMAX_H3_SMOKE_NUM_FRAMES, 128, 128, 3)
        assert output.video.dtype == torch.uint8
        assert output.audio.ndim == 3
        assert output.audio.shape[:2] == (1, 2)
        assert output.audio.shape[-1] > 0
        assert torch.isfinite(output.audio).all()
        assert output.frame_rate == 24.0
        assert output.audio_sample_rate > 0

        conditioned_output = pipeline.forward(
            prompt="Move smoothly between the supplied keyframes",
            seed=MINIMAX_H3_SEED,
            height=128,
            width=128,
            num_frames=MINIMAX_H3_SMOKE_NUM_FRAMES,
            frame_rate=24.0,
            num_inference_steps=2,
            keyframes=[
                Image.new("RGB", (128, 128), "navy"),
                Image.new("RGB", (128, 128), "orange"),
            ],
            keyframe_anchors=("first", "last"),
        )
        assert conditioned_output.video.shape == (
            1,
            MINIMAX_H3_SMOKE_NUM_FRAMES,
            128,
            128,
            3,
        )
        assert conditioned_output.audio.shape[:2] == (1, 2)
        assert torch.isfinite(conditioned_output.audio).all()
    finally:
        del conditioned_output
        del output
        del pipeline
        _cleanup_cuda()


@pytest.mark.skipif(
    os.environ.get("MINIMAX_H3_E2E_AUTHORIZED") != "1",
    reason="MiniMax-H3 checkpoint use in this CI territory requires written authorization",
)
@pytest.mark.skipif(not torch.cuda.is_available(), reason="CUDA not available")
def test_minimax_h3_public_visual_gen_api_smoke() -> None:
    """Generate joint video/audio through the public VisualGen executor API."""
    from tensorrt_llm import VisualGen, VisualGenArgs, VisualGenParams
    from tensorrt_llm.visual_gen.args import CompilationConfig, TorchCompileConfig

    checkpoint_path = _authorized_checkpoint_path()
    _disable_inductor_compile_worker_quiesce()
    visual_gen = VisualGen(
        model=checkpoint_path,
        args=VisualGenArgs(
            model=checkpoint_path,
            compilation_config=CompilationConfig(skip_warmup=True),
            torch_compile_config=TorchCompileConfig(enable=True),
        ),
    )
    try:
        output = visual_gen.generate(
            inputs="A red fox walking through snow",
            params=VisualGenParams(
                seed=MINIMAX_H3_SEED,
                height=128,
                width=128,
                num_frames=MINIMAX_H3_SMOKE_NUM_FRAMES,
                frame_rate=24.0,
                num_inference_steps=2,
            ),
        )
        assert output.video.shape == (
            1,
            MINIMAX_H3_SMOKE_NUM_FRAMES,
            128,
            128,
            3,
        )
        assert output.video.dtype == torch.uint8
        assert output.audio.shape[:2] == (1, 2)
        assert torch.isfinite(output.audio).all()
        assert output.frame_rate == 24.0
        assert output.audio_sample_rate == 32000
    finally:
        visual_gen.shutdown()
        del visual_gen
        _cleanup_cuda()


@pytest.mark.skipif(
    os.environ.get("MINIMAX_H3_E2E_AUTHORIZED") != "1",
    reason="MiniMax-H3 checkpoint use in this CI territory requires written authorization",
)
@pytest.mark.skipif(not torch.cuda.is_available(), reason="CUDA not available")
def test_minimax_h3_t2va_diffusers_lpips_and_audio_golden() -> None:
    """Gate video and audio against the pinned Diffusers implementation."""
    from tensorrt_llm._torch.visual_gen.pipeline_loader import PipelineLoader
    from tensorrt_llm.visual_gen.args import TorchCompileConfig, VisualGenArgs

    checkpoint_path = _authorized_checkpoint_path()
    _disable_inductor_compile_worker_quiesce()
    golden_path = _required_authorized_path(
        "MINIMAX_H3_DIFFUSERS_GOLDEN",
        "MiniMax-H3 Diffusers tensor golden",
        is_dir=False,
    )
    golden_video, golden_audio = _load_diffusers_golden(golden_path)

    pipeline = PipelineLoader(
        VisualGenArgs(
            model=checkpoint_path,
            torch_compile_config=TorchCompileConfig(enable=True),
        )
    ).load(skip_warmup=True)
    try:
        output = pipeline.forward(
            prompt=MINIMAX_H3_PROMPT,
            seed=MINIMAX_H3_SEED,
            height=MINIMAX_H3_QUALITY_HEIGHT,
            width=MINIMAX_H3_QUALITY_WIDTH,
            num_frames=MINIMAX_H3_QUALITY_NUM_FRAMES,
            frame_rate=24.0,
            num_inference_steps=MINIMAX_H3_NUM_INFERENCE_STEPS,
        )
        generated_video = output.video.detach().cpu()
        generated_audio = output.audio.detach().cpu()
    finally:
        del pipeline
        _cleanup_cuda()

    lpips_distance = _mean_lpips_distance(generated_video, golden_video)
    audio_distance = _multi_resolution_log_stft_distance(
        generated_audio,
        golden_audio,
    )
    print(
        "MiniMax-H3 quality: "
        f"LPIPS={lpips_distance:.6f} "
        f"(threshold={MINIMAX_H3_LPIPS_THRESHOLD:.6f}), "
        f"audio_log_stft={audio_distance:.6f} "
        f"(threshold={MINIMAX_H3_AUDIO_LOG_STFT_THRESHOLD:.6f})"
    )

    assert lpips_distance < MINIMAX_H3_LPIPS_THRESHOLD
    assert audio_distance < MINIMAX_H3_AUDIO_LOG_STFT_THRESHOLD
