name: Sync with Upstream

on:
  schedule:
    - cron: '0 7 * * 1' # Runs at 07:00 every Monday and Thursday
  workflow_dispatch: # Allows manual triggering

jobs:
  sync_with_upstream:
    runs-on: ubuntu-latest
    name: Rebase master with upstream latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          ref: main
          fetch-depth: 10 # Increase if you have more commits

      - name: Rebase upstream changes
        uses: imba-tjd/rebase-upstream-action@master
        with:
          upstream: 'NVIDIA/TensorRT-LLM'
          branch: main

