# Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause
"""Pure-Python finite coordinate mappings used by kernel code generation."""

import inspect
from dataclasses import dataclass
from math import prod
from typing import Callable, Mapping, Sequence


class FunctionMappingError(ValueError):
    """Raised when a finite function mapping is malformed."""


@dataclass(frozen=True)
class CoordinateSpace:
    """A finite named coordinate space with axis 0 linearized fastest."""

    names: tuple[str, ...]
    sizes: tuple[int, ...]

    def __post_init__(self) -> None:
        names = tuple(self.names)
        sizes = tuple(self.sizes)
        if not names or len(names) != len(sizes):
            raise FunctionMappingError(f"Coordinate-space rank mismatch: {names!r}, {sizes!r}.")
        if any(not isinstance(name, str) or not name for name in names):
            raise FunctionMappingError("Axis names must be non-empty strings.")
        if len(set(names)) != len(names):
            raise FunctionMappingError(f"Axis names must be unique: {names!r}.")
        if any(not isinstance(size, int) or size <= 0 for size in sizes):
            raise FunctionMappingError(f"Axis sizes must be positive Python ints: {sizes!r}.")
        object.__setattr__(self, "names", names)
        object.__setattr__(self, "sizes", sizes)

    @property
    def size(self) -> int:
        return prod(self.sizes)

    def axis_size(self, name: str) -> int:
        try:
            return self.sizes[self.names.index(name)]
        except ValueError as error:
            raise KeyError(f"Unknown coordinate axis {name!r}.") from error

    def delinearize(self, linear_index: int) -> tuple[int, ...]:
        if linear_index < 0 or linear_index >= self.size:
            raise FunctionMappingError(f"Linear index {linear_index} is outside [0, {self.size}).")
        remaining = linear_index
        coordinate = []
        for size in self.sizes:
            coordinate.append(remaining % size)
            remaining //= size
        return tuple(coordinate)

    def coordinates(self) -> tuple[tuple[int, ...], ...]:
        return tuple(self.delinearize(index) for index in range(self.size))


MappingResult = int | Sequence[int] | Mapping[str, int]


@dataclass(frozen=True)
class FunctionMapping:
    """A finite coordinate mapping generated by a deterministic Python function."""

    domain: CoordinateSpace
    codomain: CoordinateSpace
    function: Callable[..., MappingResult]

    def __post_init__(self) -> None:
        if not callable(self.function):
            raise FunctionMappingError("FunctionMapping.function must be callable.")
        self._validate_signature()
        for domain_coordinate in self.domain.coordinates():
            arguments = dict(zip(self.domain.names, domain_coordinate))
            result = self.function(**arguments)
            self._normalize_result(result, validate_static=True)

    def _validate_signature(self) -> None:
        signature = inspect.signature(self.function)
        parameters = signature.parameters
        unsupported = [
            name
            for name, parameter in parameters.items()
            if parameter.kind
            in (
                inspect.Parameter.POSITIONAL_ONLY,
                inspect.Parameter.VAR_POSITIONAL,
                inspect.Parameter.VAR_KEYWORD,
            )
            or parameter.default is not inspect.Parameter.empty
        ]
        if unsupported:
            raise FunctionMappingError(f"Unsupported mapping parameters {unsupported!r}.")
        if set(parameters) != set(self.domain.names):
            raise FunctionMappingError(
                f"Mapping parameters {tuple(parameters)!r} must match "
                f"domain axes {self.domain.names!r}."
            )

    def _normalize_result(
        self,
        result,
        *,
        validate_static: bool,
    ) -> dict[str, object]:
        if isinstance(result, Mapping):
            if set(result) != set(self.codomain.names):
                raise FunctionMappingError(
                    f"Mapping result keys {tuple(result)!r} must match "
                    f"codomain axes {self.codomain.names!r}."
                )
            coordinate = {name: result[name] for name in self.codomain.names}
        elif isinstance(result, Sequence) and not isinstance(
            result,
            (str, bytes),
        ):
            if len(result) != len(self.codomain.names):
                raise FunctionMappingError(
                    f"Mapping result rank {len(result)} must equal {len(self.codomain.names)}."
                )
            coordinate = dict(zip(self.codomain.names, result))
        elif len(self.codomain.names) == 1:
            coordinate = {self.codomain.names[0]: result}
        else:
            raise FunctionMappingError(
                "A multi-axis mapping must return a sequence or named mapping."
            )

        if validate_static:
            for name, value in coordinate.items():
                if not isinstance(value, int):
                    raise FunctionMappingError(
                        f"Static result {name!r} must be int, got {type(value)}."
                    )
                size = self.codomain.axis_size(name)
                if value < 0 or value >= size:
                    raise FunctionMappingError(
                        f"Static result {name!r}={value} is outside [0, {size})."
                    )
        return coordinate

    def evaluate(self, **domain_coordinate) -> dict[str, object]:
        if set(domain_coordinate) != set(self.domain.names):
            raise FunctionMappingError(
                f"Mapping arguments {tuple(domain_coordinate)!r} must match "
                f"domain axes {self.domain.names!r}."
            )
        return self._normalize_result(
            self.function(**domain_coordinate),
            validate_static=False,
        )


__all__ = [
    "CoordinateSpace",
    "FunctionMapping",
    "FunctionMappingError",
]
